[wlan][policy] Report correct line number on SME test helpers
Reports the line number of the caller when assertions fail in the SME
stream test helper.

i.e. show this:

```
thread 'main' panicked at 'unexpected variant: Pending',
../../src/connectivity/wlan/wlancfg/src/client/scan.rs:1876:9`
```

instead of this:

```
thread 'main' panicked at 'unexpected variant: Pending',
../../src/connectivity/wlan/wlancfg/src/util/testing/sme_stream.rs:30:9

```

Supersedes fxrev.dev/468977

Test: fx test wlancfg-tests
Change-Id: I4b86dfe1f16fd53a50519d98088d06617e97e0dc
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/469880
Fuchsia-Auto-Submit: Marc Khouri <mnck@google.com>
Reviewed-by: Kevin Sakuma <sakuma@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>