Revert "[starnix] Use VmexResource to make executable memory"
This reverts commit f07617408e643258cdd47b1b34b63b18c6f1a624.

Reason for revert:  CI failing with

[108216/183269] RUST starnix_runner exe.unstripped/starnix_runner
FAILED: starnix_runner exe.unstripped/starnix_runner
mkdir -p ./exe.unstripped &&  RUST_BACKTRACE=1 ../../prebuilt/third_party/rust/linux-x64/bin/rustc --color=always --crate-name starnix_runner ../../src/proc/bin/starnix/main.rs --crate-type bin --e…
error: variable does not need to be mutable
  --> ../../src/proc/bin/starnix/fs/fidl_file.rs:25:13
   |
25 |         let mut service = fkernel::VmexResourceSynchronousProxy::new(client_end);
   |             ----^^^^^^^
   |             |
   |             help: remove this `mut`
   |
   = note: `-D unused-mut` implied by `-D warnings`

error: aborting due to previous error




Original change's description:
> [starnix] Use VmexResource to make executable memory
>
> Previously, we needed to disable the security check in the kernel.
>
> Change-Id: Ib843daa2ad304e66abb741859be425f2442928a0
> Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/519408
> Reviewed-by: Drew Fisher <zarvox@google.com>
> Reviewed-by: Theodore Dubois <tbodt@google.com>
> Commit-Queue: Adam Barth <abarth@google.com>

TBR=abarth@google.com,zarvox@google.com,tbodt@google.com

Change-Id: Ia39677f4fc9d20fa32b1b8708a327cd55b9a46c1
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/519660
Reviewed-by: Scott Graham <scottmg@google.com>
Commit-Queue: Scott Graham <scottmg@google.com>