[pseudo-fs-mt] Fixed compiler throwing unused variable warning
+ Added tests module to pseudo_directory.rs
* Moved use fidl_fuchsia_io::MAX_FILENAME and test functions to said module

Build complains with

error: unused import: `fidl_fuchsia_io::MAX_FILENAME`
 -->
 ../../garnet/public/rust/fuchsia-vfs/pseudo-fs-mt/src/pseudo_directory.rs:7:6
   |
   7 | use {fidl_fuchsia_io::MAX_FILENAME, fuchsia_zircon::Status,
   proc_macro_hack::proc_macro_hack};
     |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
         = note: `-D unused-imports` implied by `-D warnings`

         error: aborting due to previous error

when attempting to use this in component_manager for 37392

Bug: 37392
Change-Id: Ib1f7f4fe24cf95e7dff6922c234e80001b7ddf93