[build] Suppress -Wunused-but-set-variable in ath10k
This patch suppresses -Wunused-but-set-variable warning in
atheros/ath10k third party code that does not comply with.

The code that causes the issues is as the following:
../../src/connectivity/wlan/drivers/third_party/atheros/ath10k/swap.c:86:12: error: variable 'seg_size' set but not used

Bug: 77973
Change-Id: I63e2c40f36deb10cf49b131628594dfbb378546a
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/550729
Reviewed-by: Alex Legg <alexlegg@google.com>
Commit-Queue: Gulfem Savrun Yeniceri <gulfem@google.com>