[escher] Fix uint64_t to uint32_t error
For some reason, this error only appears on the clang canary builders.

error: implicit conversion loses integer precision: 'long' to 'uint32_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
      ((latch_time - pose_buffer.base_time) / pose_buffer.time_interval) % pose_buffer.num_entries;
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~

Fix so this will help unblock the next clang roll.

TEST=Tested locally with the new clang revision.

Change-Id: Ib81fcfa31d81e999356bf8ae61582f764da89a37
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/433522
Reviewed-by: Petr Hosek <phosek@google.com>
Testability-Review: Petr Hosek <phosek@google.com>
Commit-Queue: Leonard Chan <leonardchan@google.com>