[fidl][rust] Mark QueryResponseFut with T: Unpin
When compiling with the latest futures 0.3.9 (rather than the 0.3.6 we
currently have pinned), I saw the following compilation error:

error[E0277]: `T` cannot be unpinned
on lines 78 and 79 of src/lib/fidl/rust/fidl/src/client.rs:78
(full error message at go/paste/5141922172633088)

The compiler suggested restricting T with `T: Unpin`, which resolved the
compilation error (without causing any new ones). As I understand it,
that means all the types used with QueryResponseFut were already Unpin.

Test: no behavior change expected
Change-Id: Icf8ee550bf48d558596c1c810480a1a57c926b74
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/469997
Reviewed-by: Marie Janssen 💖 <jamuraa@google.com>
Reviewed-by: Tyler Mandry <tmandry@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Fuchsia-Auto-Submit: Marc Khouri <mnck@google.com>