[async] add missing \n at the end of the file
Fuchsia seems pretty lenient, but Crashpad is not: "pkg/async/include/lib/async/wait.h:74:29: error: no newline at end of file [-Werror,-Wnewline-eof]" and this file is included in the SDK

TC-442 #comment

Change-Id: I3c24d25a6c8a84f907a31c132ee47661f9764ec6