[assembly] Improve Exception Handling
When running assembly Python scripts, the exceptions that are raised
often result in failing the assembly process. The exception messages are
raw stacktraces as the result of the exception not being caught and
converted into a client appropriate message.

The logging framework in the Python standard library provides an
interface for presenting exceptions in a more client appropriate form,
through the `logger.exception(message: str)` method. This commit
utilizes the logging library in the main() invocations for various
scripts, and subclasses the Exception class to provide useful feedback
to the user regarding the nature of the failure.

Directly Raised Exception (parent commit)
```
Traceback (most recent call last):
  File "/usr/local/google/home/youngda/.scratch/pretty_print_exceptions.py", line 16, in main
    raise Exception("Trouble parsing a json file")
Exception: Trouble parsing a json file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/google/home/youngda/.scratch/pretty_print_exceptions.py", line 33, in <module>
    main()
  File "/usr/local/google/home/youngda/.scratch/pretty_print_exceptions.py", line 18, in main
    raise PackageManifestParseException(
__main__.PackageManifestParseException: The package manifest couldn't be parsed
```

With logger.exception() (suggested change)
```
logger.exception() call: This is the only line of helpful information we can really include, and it slightly obfuscates the traceback. That said, it does help us isolate the exact location of the exception being thrown, less the stacktrace that proceeds it.

Traceback (most recent call last):
  File "/usr/local/google/home/youngda/.scratch/pretty_print_exceptions.py", line 16, in main
    raise Exception("Trouble parsing a json file")
Exception: Trouble parsing a json file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/google/home/youngda/.scratch/pretty_print_exceptions.py", line 18, in main
    raise PackageManifestParseException(
PackageManifestParseException: The package manifest couldn't be parsed
```

Bug: 110818 (follow-up commit)

Tests: `fx test -o test_make_legacy_config`
Change-Id: Ie7e15a1085da55504c67f69c27dabcb1e1491be8
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/748765
Reviewed-by: Aaron Wood <aaronwood@google.com>
Commit-Queue: Daniel Young <youngda@google.com>