[zircon][usb-mass-storage] Use std::variant instead of union for usb_descriptor
With the tip-of-tree Clang, this is failing to compile because the
-Winvalid-constexpr has gotten more strict:

  usb-mass-storage.cpp:30:37: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
      static constexpr usb_descriptor Create(usb_endpoint_descriptor_t descriptor) {
                                      ^
  usb-mass-storage.cpp:32:25: note: member call on member 'endpoint' of union with active member 'interface' is not allowed in a constant expression
          retval.endpoint = descriptor;
                          ^
  1 error generated.

Use std::variant instead of union to avoid this error.

Change-Id: Iedfb4fd716f32d8d354dc47d78b566a5f39b189e