[build] Suppress -Wunused-but-set-var in boringssl
This patch suppresses -Wunused-but-set-variable warning in
boringssl third party code that does not comply with.

The code that causes the issue is as the following:
../../third_party/boringssl/src/crypto/x509/t_x509.c:326:18: error:
variable 'l' set but not used

Bug: 96269
Change-Id: Ib917d93e6d3a96ca582a90eacecbe3ad43ace706
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/662282
Fuchsia-Auto-Submit: Gulfem Savrun Yeniceri <gulfem@google.com>
Reviewed-by: Petr Hosek <phosek@google.com>
Commit-Queue: Gulfem Savrun Yeniceri <gulfem@google.com>