[fvdl] Improve error message when starting fvdl
When a user tries to run fvdl or ffx emu from the SDK, but they forget
the --sdk flag, the error it prints is:

Error: Cannot read path info from root_dir None

This is not helpful for debugging the reason for the failure, which is
that the user needs to run in the Fuchsia directory and include the
--sdk flag.

This CL changes the error message to be more helpful for the users and
explain how to get past the problem.

Bug: 80407
Change-Id: Iefa86d5789adb9975e8256ba917dc36c7f2fd434
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/556603
Commit-Queue: Daniel Dougherty <doughertyda@google.com>
Reviewed-by: Yuan Zhi <yuanzhi@google.com>