[build] Suppress -Wunused-but-set-par/var in dash
This patch suppresses -Wunused-but-set-parameter and
-Wunused-but-set-variable warnings in dash third party
code that does not comply with.

The code that causes the issues is as the following:
1) zircon/third_party/uapp/dash/src/eval.c:557:29: error: parameter
'flags' set but not used
2) zircon/third_party/uapp/dash/src/bltin/zircon.c:187:9: error:
variable 'count' set but not used

Bug: 77973
Change-Id: I0d5a70704783d089da7025662b0caf227074466c
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/550736
Commit-Queue: Gulfem Savrun Yeniceri <gulfem@google.com>
Reviewed-by: Shai Barack <shayba@google.com>