[build] Suppress -Wunused-but-set-variable in brcmfmac
This patch suppresses -Wunused-but-set-variable warnings
that broadcom/brcmfmac code does not comply with.
The code that causes the issues is as the following:
1) ../../src/connectivity/wlan/drivers/third_party/broadcom/brcmfmac/chip.cc:793:11:
error: variable 'mpnum' set but not used
2) ../../src/connectivity/wlan/drivers/third_party/broadcom/brcmfmac/chip.cc:870:11:
error: variable 'nmp' set but not used
3) ../../src/connectivity/wlan/drivers/third_party/broadcom/brcmfmac/chip.cc:870:16:
error: variable 'nsp' set but not used
4) ../../src/connectivity/wlan/drivers/third_party/broadcom/brcmfmac/cfg80211.cc:586:15:
error: variable 'iface_role_name' set but not used
5) ../../src/connectivity/wlan/drivers/third_party/broadcom/brcmfmac/cfg80211.cc:4903:31:
error: variable 'cfg' set but not used

Bug: 77973
Change-Id: I01aec02710049ab3daf59f8e135b0ab164bea06f
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/550047
Commit-Queue: Gulfem Savrun Yeniceri <gulfem@google.com>
Reviewed-by: Suraj Malhotra <surajmalhotra@google.com>