Revert "[libc] explicitly whitelist exported libc symbols"
This reverts commit 4785254d8d5a22c5f41a5f16433b5924546b5731.

Reason for revert: boringssl depends on getauxval()

  FAILED: arm64-shared/libcrypto.so
  arm64-shared/lib.unstripped/libcrypto.so
  /b/s/w/ir/kitchen-workdir/cipd/goma/gomacc
  ../../buildtools/linux-x64/clang/bin/clang++ -shared -Wl,--threads
  --sysroot=/b/s/w/ir/kitchen-workdir/out/build-zircon/build-user-arm64/sysroot
  --target=aarch64-fuchsia -g -Og -Wl,--icf=all -fsanitize=safe-stack
  -fstack-protector-strong -Wl,--no-undefined -o
  "arm64-shared/lib.unstripped/libcrypto.so" -Wl,-soname="libcrypto.so"
  @"arm64-shared/libcrypto.so.rsp" &&
  ../../buildtools/linux-x64/clang/bin/llvm-objcopy --strip-all
  "arm64-shared/lib.unstripped/libcrypto.so" "arm64-shared/libcrypto.so"
  /b/s/w/ir/kitchen-workdir/out/debug-aarch64/../../buildtools/linux-x64/clang/bin/ld.lld:
  error: undefined symbol: getauxval
  >>> referenced by cpu-aarch64-linux.c:29
  (../../third_party/boringssl/src/crypto/cpu-aarch64-linux.c:29)
  >>>
  arm64-shared/obj/third_party/boringssl/src/crypto/libcrypto.cpu-aarch64-linux.o:(OPENSSL_cpuid_setup)
  clang-7.0: error: ld.lld command failed with exit code 1 (use -v to see
  invocation

Original change's description:
> [libc] explicitly whitelist exported libc symbols
> 
> In an effort to help pin down the libc APIs we plan on supporting, move
> to an explicit whitelist model for exported libc symbols. This will
> allow us to better document and control our exposed APIs, and avoid
> others depending on functionality we don't want to support.
> 
> Of the 1494 symbols originally exported by musl, only 683 of them are
> actually used. The remaining 811 symbols are unused.
> 
> Build a whitelist based on the 683 symbols actually used, plus other
> symbols recommended during code review. In particular, libm functions
> are generally considered safe and easy to maintain because they don't
> modify global state, so add an additional 200 libm symbols.
> 
> This whitelist isn't a statement of what we will or won't support.
> However, it provides a baseline where functions can be added or
> removed over time.
> 
> The net effect of this change is to remove the following symbols from
> libc:
> 
>   a64l acct addmntent adjtime alphasort asctime asctime_r
>   at_quick_exit bcmp bcopy bindtextdomain
>   bind_textdomain_codeset bsd_signal c16rtomb c32rtomb
>   call_once catclose catgets catopen __c_dot_utf8
>   __c_dot_utf8_locale clearenv clearerr_unlocked __c_locale
>   clock_getcpuclockid clock_getres clock_nanosleep
>   clock_settime confstr __cos __cosdf __cosl ctermid ctime_r
>   __ctype_b_loc __ctype_tolower_loc __ctype_toupper_loc
>   cuserid __cxa_finalize dallocx dcgettext dcngettext
>   dgettext _dl_debug_addr _dl_debug_state dlinfo
>   __dn_comp dn_comp __dn_expand dngettext dn_skipname
>   __dns_parse dprintf drem dremf duplocale __duplocale
>   eaccess ecvt endhostent endmntent endnetent endprotoent
>   endservent endspent _environ __environ ___environ erand48
>   ether_aton ether_aton_r ether_hostton ether_line ether_ntoa
>   ether_ntoa_r ether_ntohost euidaccess execle execvpe
>   __execvpe _Exit __expo2 __expo2f fchdir fcvt feclearexcept
>   fegetenv fegetexceptflag fegetround feholdexcept
>   feof_unlocked feraiseexcept ferror_unlocked fesetenv
>   fesetexceptflag fesetround fetestexcept feupdateenv fexecve
>   ffsl fgetc_unlocked fgetgrent fgetln fgetpos fgetpwent
>   fgetspent fgets_unlocked __fgetwc_unlocked fgetwc_unlocked
>   fgetws fgetws_unlocked fileno_unlocked flock flockfile
>   __flt_rounds fpathconf fputc_unlocked fputs_unlocked fputwc
>   __fputwc_unlocked fputwc_unlocked fputws fputws_unlocked
>   __freelocale fsetpos __fstatfs ftime ftok ftrylockfile
>   funlockfile futimesat __futimesat fwide fwprintf fwscanf
>   gcvt getauxval getchar_unlocked getc_unlocked
>   get_current_dir_name getdate getdate_err getdelim
>   __getdelim getdomainname getdtablesize __getgr_a getgrent
>   __getgrent_a gethostbyaddr_r gethostbyname2 gethostbyname_r
>   gethostent gethostid getitimer getlogin getlogin_r
>   getmntent getmntent_r getnetbyaddr getnetbyname getnetent
>   getopt_long_only __getopt_msg getpass getpriority
>   getprotobyname getprotobynumber getprotoent __getpw_a
>   getpwent __getpwent_a __get_resolv_conf getrlimit gets
>   getservbyname_r getservbyport_r getservent getspent
>   getspnam_r getsubopt gettext __gettextdomain getw getwc
>   getwchar getwchar_unlocked getwc_unlocked glob globfree
>   __gmtime_r hasmntopt herror if_freenameindex if_nameindex
>   imaxdiv index __inet_aton inet_lnaof inet_makeaddr
>   inet_netof inet_network initstate __invtrigl_R
>   _IO_feof_unlocked _IO_ferror_unlocked _IO_getc
>   _IO_getc_unlocked _IO_putc _IO_putc_unlocked isascii
>   isastream issetugid iswalnum iswctype iswgraph jrand48
>   killpg l64a lchmod lckpwdf lcong48 __ldexp_cexp
>   __ldexp_cexpf __lgammaf_r lgammaf_r __lgammal_r
>   lgammal_r __lgamma_r lgamma_r __libc_current_sigrtmax
>   __libc_current_sigrtmin __localtime_r lockf
>   _longjmp __lookup_ipliteral __lookup_serv lrand48 lutimes
>   __madvise mallctlbymib mallctlnametomib malloc_conf
>   malloc_message malloc_stats_print malloc_usable_size
>   mallocx __map_file mblen mbrtoc16 mbrtoc32 mbsinit mbstowcs
>   memccpy memrchr __memrchr mkfifoat mknodat mkostemp
>   mkostemps __mkostemps mkostemps64 mkstemps mlock mlockall
>   __mmap __mprotect mrand48 msgctl msgget msgrcv msgsnd msync
>   munlock munlockall __munmap nallocx __newlocale ngettext
>   nice __nl_langinfo __nl_langinfo_l nl_langinfo_l nrand48
>   _ns_flagdata ns_initparse ns_name_uncompress ns_parserr
>   ns_put16 ns_put32 ns_skiprr open_memstream openpty
>   open_wmemstream opterr __optpos __optreset __overflow
>   __p1evll __parsespent pathconf __pleval __polevll
>   posix_close __posix_getopt posix_madvise posix_openpt
>   posix_spawn posix_spawnattr_destroy
>   posix_spawnattr_getflags posix_spawnattr_getpgroup
>   posix_spawnattr_getschedp posix_spawnattr_getschedp
>   posix_spawnattr_getsigdef posix_spawnattr_getsigmas
>   posix_spawnattr_init posix_spawnattr_setflags
>   posix_spawnattr_setpgroup posix_spawnattr_setschedp
>   posix_spawnattr_setschedp posix_spawnattr_setsigdef
>   posix_spawnattr_setsigmas posix_spawn_file_actions_
>   posix_spawn_file_actions_ posix_spawn_file_actions_
>   posix_spawn_file_actions_ posix_spawn_file_actions_
>   posix_spawnp __posix_spawnx pow10 pow10f pow10l __progname
>   __progname_full program_invocation_name
>   program_invocation_short_ psiginfo psignal pthread_atfork
>   pthread_attr_getdetachsta pthread_attr_getguardsize
>   pthread_attr_getinheritsc pthread_attr_getschedpara
>   pthread_attr_getschedpoli pthread_attr_getscope
>   pthread_attr_setguardsize pthread_attr_setinheritsc
>   pthread_attr_setschedpara pthread_attr_setschedpoli
>   pthread_attr_setscope pthread_barrierattr_destr
>   pthread_barrierattr_init pthread_cancel
>   pthread_condattr_getclock pthread_getaffinity_np
>   pthread_getconcurrency pthread_getcpuclockid
>   pthread_getschedparam pthread_kill
>   pthread_mutexattr_getprot pthread_mutexattr_getrobu
>   pthread_mutexattr_gettype pthread_mutexattr_setprot
>   pthread_mutexattr_setrobu pthread_mutex_consistent
>   pthread_mutex_getprioceil pthread_mutex_setprioceil
>   pthread_mutex_timedlock __pthread_mutex_trylock_o
>   pthread_rwlockattr_destro pthread_rwlockattr_init
>   pthread_rwlock_timedrdloc pthread_rwlock_timedwrloc
>   pthread_rwlock_tryrdlock pthread_rwlock_trywrlock
>   pthread_setaffinity_np pthread_setcancelstate
>   pthread_setcanceltype pthread_setconcurrency
>   pthread_setschedparam pthread_setschedprio
>   pthread_spin_destroy pthread_spin_init pthread_spin_lock
>   pthread_spin_trylock pthread_spin_unlock pthread_testcancel
>   __ptsname_r ptsname_r putchar_unlocked putc_unlocked
>   putgrent putpwent putspent putw putwc putwchar
>   putwchar_unlocked putwc_unlocked quick_exit rallocx
>   __randname __rem_pio2 __rem_pio2f __rem_pio2l
>   __rem_pio2_large __res_mkquery res_mkquery __res_msend
>   __res_msend_rc __res_query res_querydomain res_search
>   __res_send res_send rindex __rtnetlink_enumerate sallocx
>   __sanitizer_before_thread __sanitizer_log_write
>   __sanitizer_shadow_bounds __sanitizer_startup_hook
>   __sanitizer_thread_create __sanitizer_thread_exit_h
>   __sanitizer_thread_start_ scandir sched_getcpu
>   sched_getparam sched_get_priority_max
>   sched_get_priority_min sched_getscheduler
>   sched_rr_get_interval sched_setparam sched_setscheduler
>   sdallocx seed48 semctl semget semop semtimedop sem_unlink
>   setbuffer setdomainname setgrent sethostent setitimer
>   _setjmp setlogmask setmntent setnetent setpgrp setpriority
>   setprotoent setpwent setservent setspent setstate
>   settimeofday __shgetc __shlim shmat shmctl shmdt shmget
>   __shm_mapname shm_open shm_unlink sigaltstack sigandset
>   sigdelset sighold sigignore siginterrupt sigisemptyset
>   sigismember signgam __signgam sigorset sigpause sigpending
>   sigqueue sigrelse sigset sigsuspend sigtimedwait sigwait
>   sigwaitinfo __sin __sindf __sinl statfs __statfs stime
>   __stpcpy stpncpy __stpncpy strcasestr __strchrnul __strdup
>   strfmon strfmon_l __strftime_fmt_1 __strtod_l strtod_l
>   __strtof_l strtof_l __strtold_l strtold_l strverscmp
>   stub_pselect stub_select swab swscanf __sysv_signal __tan
>   __tandf __tanl tcdrain tcflow tcflush tcgetsid tcsetpgrp
>   tempnam textdomain thrd_equal thrd_exit thrd_sleep timegm
>   __tm_to_tzname toascii towctrans __tre_mem_alloc_impl
>   __tre_mem_destroy __tre_mem_new_impl tss_create tss_delete
>   tss_get tss_set __tzset ualarm __uflow ulckpwdf ulimit
>   ungetwc __unsanitized_memcpy __unsanitized_memmove
>   __unsanitized_memset __uselocale valloc vdprintf verrx
>   versionsort vfork __vfork vfscanf vfwprintf vfwscanf vscanf
>   vswprintf vswscanf vsyslog __vsyslog vwarn vwarnx vwprintf
>   vwscanf wait __wait waitid wcpcpy wcpncpy wcscasecmp wcscat
>   wcschr wcscpy wcscspn wcsdup wcsftime __wcsftime_l
>   wcsftime_l wcsncasecmp wcsncat wcsncmp wcsncpy wcsnlen
>   wcspbrk wcsrchr wcsrtombs wcsspn wcstoimax wcstok wcstombs
>   wcstoumax wcswcs wcswidth wctomb wctrans wctype wordexp
>   wordfree wprintf wscanf xallocx __xpg_basename
>   __xpg_strerror_r
> 
> Change-Id: I23a3b7d4cbc801143e4c3a08a8dfc86224752fb6

TBR=kulakowski@google.com,smklein@google.com,swetland@google.com,mcgrathr@google.com,jeffbrown@google.com,nnk@google.com

Change-Id: I222e324a6b162b51d77e825235ae0c3690514c0b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true