[unification] Move //zircon/system/utest/zxcrypt to the GN build
Generated with: //scripts/unification/move_zn_element.py

Fixed up the slightly-stricter build flags around unused code.

scripts/unification/verify_element_move.py --reference local/initial.json
gives some changes, all of which seem reasonable and
not particularly concerning:

Error     aux         shared library removed from test/sys/zxcrypt-test: libkeysafe.so
Warning   aux         shared library added to test/sys/zxcrypt-test: libdevmgr-launcher.so
Warning   aux         shared library added to test/sys/zxcrypt-test: libdriver-integration-test.so
Error     tests       shared library removed from test/sys/zxcrypt-test: libkeysafe.so
Warning   tests       shared library added to test/sys/zxcrypt-test: libdevmgr-launcher.so
Warning   tests       shared library added to test/sys/zxcrypt-test: libdriver-integration-test.so
Error: summaries do not match!

The libkeysafe.so removal is fine; libkeysafe.so has no symbols and is
an artifact of the fact that zircon libraries can't actually be
headers-only (which keysafe here is).

The additional shared libraries are reasonable -- this test uses
IsolatedDevmgr, so it's not surprising that it uses the appropriate
shared libraries.

Change-Id: I1ff48a6624d735dc949c08b7e7df40518cbad67c