Reland "[kernel] Use PinnedVmObject::reset instead of ktl::move"
This reverts commit 0c54daca5e6dbd4ff52ed5de1ee81443a4fe724d.

Reason for revert: Revert not fix the build.

Original change's description:
> Revert "[kernel] Use PinnedVmObject::reset instead of ktl::move"
>
> This reverts commit fd979cbb7a73a2ff2be8d601c9d4f36c3a03eb7d.
>
> Reason for revert: Suspected cause of https://fxbug.dev/108834.
>
> Original change's description:
> > [kernel] Use PinnedVmObject::reset instead of ktl::move
> >
> > We're relying on ktl::move to run the destructor of PinnedVmObject
> > ignoring the result value, but this is triggering an error in the
> > tip-of-tree Clang:
> >
> >     ../../zircon/kernel/arch/arm64/perf_mon.cc:515:5: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
> >         ktl::move(data->pinned_buffer);
> >         ^~~~~~~~~ ~~~~~~~~~~~~~~~~~~~
> >     1 error generated.
> >
> > Use PinnedVmObject::reset instead which has the same effect.
> >
> > Fixed: 108702
> > Change-Id: Id14a35a996804a9398b50032e1a4421e50591149
> > Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/720210
> > Reviewed-by: Roland McGrath <mcgrathr@google.com>
> > Fuchsia-Auto-Submit: Petr Hosek <phosek@google.com>
> > Commit-Queue: Petr Hosek <phosek@google.com>
>
> Change-Id: I0f52d09c65326916331f26f83910408dd7746b18
> Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/722531
> Reviewed-by: RubberStamper 🤖 <android-build-ayeaye@system.gserviceaccount.com>

Change-Id: I105fcc839abc6bfc3d6a1c0c30ab3c72337e71d8
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/722865
Commit-Queue: Charles Celerier <chcl@google.com>
Reviewed-by: RubberStamper 🤖 <android-build-ayeaye@system.gserviceaccount.com>