[build] Suppress -Wunused-but-set-variable in openbsd-netcat
This patch suppresses -Wunused-but-set-variable warning in
openbsd-netcat third party code that does not comply with.

The code that causes the issues is as the following:
1) ../../src/connectivity/network/tools/nc/third_party/openbsd-netcat/netcat.c:122:25:
error: variable 'socksv' set but not used
2) ../../src/connectivity/network/tools/nc/third_party/openbsd-netcat/netcat.c:129:30:
error: variable 'proxyhost' set but not used
3) ../../src/connectivity/network/tools/nc/third_party/openbsd-netcat/netcat.c:129:47:
error: variable 'proxyport' set but not used

Bug: 77973
Change-Id: I5dae28e70753e80bf06602066151689e12be942f
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/550725
Commit-Queue: Gulfem Savrun Yeniceri <gulfem@google.com>
Reviewed-by: Tamir Duberstein <tamird@google.com>