[fdio/tests] Avoid conversion warning
../../sdk/lib/fdio/tests/fdio_open_max.c:12:13: error: implicit conversion loses integer precision: 'long' to 'int' [-Werror,-Wshorten-64-to-32]
  int max = sysconf(_SC_OPEN_MAX);

Add sdk tests to buildbot, since they are apparently not included.

Restrict fdio host tests to Linux, since they do not build on MacOS.

Change-Id: If6e60377bd493261c4a0305aaaac0e9b65129dab
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/431858
Reviewed-by: John Wittrock <wittrock@google.com>
Reviewed-by: Pascal Perez <pascallouis@google.com>
Testability-Review: Pascal Perez <pascallouis@google.com>
Commit-Queue: Tamir Duberstein <tamird@google.com>