[fidlgen] Solidify assert(Not)Equal helpers
By advertising `interface{}` for values, one expects a deep comparison
rather than simply a pointer equality as was done previously. This was
fine given the use with primitives, but new uses (e.g.
I58f17d8e901942e3f1d5e297c576ab77b60d609b) are planned.

Checked by changing a test

```
-       assertEqual(t, int(Colors.Green), 2)
+       assertEqual(t, int(Colors.Green), 5)
```

yielding output

```
=== RUN   TestExample
    enum_test.go:15:
        left=2
        right=5
        diff=  int(
        -       2,
        +       5,
          )

Change-Id: Iad41790fe9a6d69effadf8d1a6244e9147b56b33
--- FAIL: TestExample (0.00s)
```
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/501982
Commit-Queue: Pascal Perez <pascallouis@google.com>
Fuchsia-Auto-Submit: Pascal Perez <pascallouis@google.com>
Reviewed-by: Yifei Teng <yifeit@google.com>