[mac] Require 10.10 SDK
NSOperatingSystemVersion, already in use, was introduced in 10.10.

../../third_party/flutter/fml/platform/darwin/platform_version.mm:11:9: error: unknown type name 'NSOperatingSystemVersion'
  const NSOperatingSystemVersion version = {
        ^

Change-Id: I218c3031a87e0b740d05b6810f41f2a0d73c89f8