Revert "[usb proto]Add complete cb as a parameter"
This reverts commit 9b5ac003952b1581ab1d7eee83da08e44d359576.

Reason for revert: This breaks global integration, due to the Broadcom drivers in Garnet.

../../garnet/drivers/wlan/third_party/broadcom/brcmfmac/usb.c:271:44: error: too few arguments to function call, expected 4, have 2
    usb_request_queue(usb_proto, urb->zxurb);
    ~~~~~~~~~~~~~~~~~                      ^
../../zircon/system/ulib/ddk/include/ddk/protocol/usb.h:191:1: note: 'usb_request_queue' declared here
static inline void usb_request_queue(const usb_protocol_t* usb, usb_request_t* usb_request,
^
1 error generated.

Original change's description:
> [usb proto]Add complete cb as a parameter
> 
> With usb request having private regions for each layer in the stack,
> the complete callback and their contexts should not be part of the public
> part of the usb-request. This changeset modifies usb protocol so that
> the complete_cb and its context are passed in as parameters.
> 
> Test: zircon build. Will be changing garnet also and then will do basic
> sanity test.
> 
> Change-Id: I42ab688b3db2aaca56f05d67a69d94b61199c256

TBR=voydanoff@google.com,jocelyndang@google.com,ravoorir@google.com,surajmalhotra@google.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Change-Id: I886923ac032e3713a9426b992a2dd542357c25c9