[sc] Better validation error messages.
Rephrased missing cvf error message for clarity and actionability.

Put package name first rather than build path, since most
users don't encounter the path within the build directory
for their package manifest.

Avoided repeating path-with-package for the value file which
makes it seem more like noise given all the other paths printed,
which required adding the path to the bootfs error as well.

Fixed: 99686
---------------------------------------------

An individual package's error before:

```
Error: Failed to validate obj/src/diagnostics/detect/triage-detect/package_manifest.json:
└── meta/triage-detect.cm: Validating structured configuration
    └── Couldn't read config values from `meta/triage-detect.cvf`.
    └── Path not present in archive: "meta/triage-detect.cvf"
```

and after:

```
Error: Failed to validate package `triage-detect`:
└── meta/triage-detect.cm: Validating structured configuration
    └── Couldn't find component's config values in package.
    └── Path not present in archive: "meta/triage-detect.cvf"
```

---------------------------------------------

A bootfs-based component's error before:

```
Product Assembly Failed
    1.  Validating product assembly failed:
    └── Failed to validate bootfs:
        └── meta/archivist.cm: Validating structured configuration
            └── Couldn't read config values from `meta/archivist.cvf`.
            └── No such file in bootfs.
```

and after:

```
Product Assembly Failed
    1.  Validating product assembly failed:
    └── Failed to validate bootfs:
        └── meta/archivist.cm: Validating structured configuration
            └── Couldn't find component's config values in package.
            └── `meta/archivist.cvf` does not exist in bootfs.
```

Change-Id: I74a014673d2853db975f811352a0bac287d1135a
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/677883
Fuchsia-Auto-Submit: Adam Perry <adamperry@google.com>
Reviewed-by: Aaron Wood <aaronwood@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>