[resultdb] Try to capture 3 lines from stderr as failure_reason
We noticed that capturing a single line from stderr produces very
generic error message: "thread 'main' panicked at 'assertion failed: `(left == right)`"

Tweak the algorithm to capture 3 lines from stderr that hopefully would
show the full error message.

Note that we originally decided to only capture a single line in
https://fxrev.dev/621322 due to concern that we may have stderr from
multiple test cases printed out of order. So this is still less
desirable compared to switching to using `ffx test`.

Examples:
no-ffx - https://ci.chromium.org/ui/p/fuchsia/builders/try/core.x64-release/b8814399138844346545/test-results
ffx - https://ci.chromium.org/ui/p/fuchsia/builders/try/core.x64-release-ffx/b8814399138844346561/test-results

Bug: 99976
Change-Id: Ia3ae9e787cc73a3fa193dd92235d871f1b61a83a
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/677893
Reviewed-by: Oliver Newman <olivernewman@google.com>
Commit-Queue: Yuan Zhi <yuanzhi@google.com>