[kernel][kcounter] Assert that kcounters are not defined in headers
Defining a kcounter in a header can lead to "split counters".  Add
a static assert to the KCOUNTER_DECLARE macro to prevent them from
being defined in a header.

Here's what the compiler error looks like if you try to define one in
handle.h:

```
In file included from ../../zircon/kernel/object/message_packet_tests.cc:13:
In file included from ../../zircon/kernel/object/include/object/message_packet.h:18:
../../zircon/kernel/object/include/object/handle.h:236:1: error: static_assert failed due to requirement '2 == 0' "kcounters should not be defined in a header as doing so may result in the creation of multiple unrelated counters with the same name"
KCOUNTER(bad_counter, "bad")
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Change-Id: I0984ce085986607fb794ce646ce4a0951055d4a2
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/453776
Reviewed-by: Carlos Pizano <cpu@google.com>
Reviewed-by: Scott Graham <scottmg@google.com>
Testability-Review: Scott Graham <scottmg@google.com>
Commit-Queue: Nick Maniscalco <maniscalco@google.com>