[rust][inspect] Allow using expression as keys in assert_inspect_tree
Note the syntax uses `=>` instead of `:`. The reason for this is that
Rust disallows `:` after an `expr` in a macro definition:

```
error: `$key:expr` is followed by `:`, which is not allowed for `expr` fragments
   --> ../../src/lib/inspect/rust/fuchsia-inspect/src/testing.rs:121:44
    |
121 |     (@build $tree_assertion:expr, $key:expr: $($rest:tt)+) => {{
    |                                            ^ not allowed after `expr` fragments
    |
    = note: allowed there are: `=>`, `,` or `;`

error: aborting due to previous error
```

TESTED=fx run-test fuchsia_inspect_tests

Change-Id: Idaac248695f3cbaa2017ab2ce6a59d907dfb6ce5