Revert "[fdf][examples] Write DFv2 demo-number example"
This reverts commit 46ff4f0db3a3979f975b9af55401e660e1462825.

Reason for revert: broke the build:
https://ci.chromium.org/b/8816988693019199633

```
examples/drivers/v2/demo-number/demo_number.cc:68:24: error: no member named 'device_client' in 'compat::Interop'
```

Original change's description:
> [fdf][examples] Write DFv2 demo-number example
>
> This is going to be the example driver for DFv2.
> Start by building the driver with the current DFv2
> libraries, but this example will be updated to
> use best practices and SDK only libraries.
>
> Bug: 97855
>
> Change-Id: If2117d93adfe0020d67b04d1388b0a1374397f52
> Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/668095
> Reviewed-by: Suraj Malhotra <surajmalhotra@google.com>
> Commit-Queue: David Gilhooley <dgilhooley@google.com>

Bug: 97855
Change-Id: I75128295fcceb8fcb519662fa12283cdf01a4348
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/668826
Reviewed-by: RubberStamper 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Commit-Queue: Oliver Newman <olivernewman@google.com>