[router-manager] Moves router-manager from /vendor/google
That includes the following commits in /vendor/google repo:

commit c19a7c14fcd2c0844d01c4b35a39296b4b90fe7a
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Thu Aug 1 00:09:54 2019 +0000

    [router-manager] Interface properties are properly applied.

    Change-Id: I0bd1c7d84d2dfb081c58b18b8f6ff1de41eea926

commit 95137e37526333e2ea547d71c8fbbf31e2072b43
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Wed Jul 24 14:56:52 2019 -0700

    [router-manager] Add and delete LIF

    Change-Id: I7b3d3e3ccd7f71a98c7d84cc260c71c3361e9dca

    Properly handle errors when creating WAN or LAN

    Make sure state is not changed when there is an error during interface
    creation.

    Change-Id: I401d42b372d80462fc6fbfe0f201bdc4fb79a6a2

commit 936ae3fb6038c3bf086625f3a09d9fcf6176f8f8
Author: Arjun <guzt@google.com>
Date:   Mon Jul 29 22:10:21 2019 +0000

    [rust][router_manager] Fix router_manager breakage

    error[E0725]: the feature `try_from` is not in the list of allowed features
     --> ../../vendor/google/bin/router_manager/core/src/lib.rs:8:12
      |
    8 | #![feature(try_from)]
      |            ^^^^^^^^

    error: aborting due to previous error

    Change-Id: Ibcb676ba704b8ccf97fd3c02a3118d8a844ceb26

commit d041dd4ec6bafc5c7bdf8feacb9668be9850b8b2
Author: Chris Gibson <cgibson@google.com>
Date:   Sat Jul 27 00:04:45 2019 +0000

    [router-mgr] fix tests

    Change-Id: I01bf1860fd0b813406e4753c692f4d7e320942c4

commit 17a2e0d60c2a158204db2312c9d4b28383434f49
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Wed Jul 24 13:21:15 2019 -0700

    [router-manager] Removes port manager dependency from LIF.

    Change-Id: I28966f4f7e0ab8d680fb886e4208f62dd76d2383

commit c5bb036dbda49e967e447d2a064372a55429daa4
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Wed Jun 19 16:53:35 2019 -0700

    [router-manager] hal.rs now uses error::Result

    This makes it consistent with the rest of the code.

    Change-Id: Ibf95de1378a6355b2ed6a383652dbf7d74ac5df3

commit aea4907467fb0a2167d91d30802f174f32c8bf70
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Thu Jul 25 15:00:25 2019 -0700

    [router-manager] Fixes broken build

    interface property path has been changed to topopath

    Change-Id: I882318c05998dc1056839d624a6b44f6683b3462

commit a63010d6315b7063100201aeeb8ae3043657d9c1
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Thu Jul 25 18:13:59 2019 +0000

    [router-mgr] Creates types for IDs.

    Change-Id: I9287e17498024baf9ca6c3f8cec816f32b25f591

commit 7c7391e02fd0caddf94e1d408bbd4e82ff7b8e6a
Author: Chris Gibson <cgibson@google.com>
Date:   Wed Jul 17 19:47:47 2019 +0000

    [router-mgr] support more fidl transforms

    This patchset adds support for more fidl transforms. We can now convert
    from `router_config::FilterRule` to `netfilter::Rule`. This allows us
    to handle a new class of API requests, such as being able to add packet
    filter rules.

    Also adds a new integration test that exercises adding a new packet
    filter rule.

    Test: Builds, runs, and all tests pass.
    Change-Id: I01d73622c59bb394177e7b0294c9b28e4c963fe5

commit a6653adbfebacec91a7531c9de4b3de21f7dd34f
Author: Arjun <guzt@google.com>
Date:   Tue Jul 16 01:59:02 2019 +0000

    [router_manager] Add case for handling newly added services from  fxr/275284

    Change-Id: I88e0682eeab0423336e57451ac98e35051ef6035

commit 522f56a93483f3b77f7eebb93ab4e12f4444f61a
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Wed Jun 19 00:17:18 2019 +0000

    [router-mgr] update to fuchsia_component

    This commit moves router_manager off the deprecated fuchsia_app
    framework and over to the new fuchsia_component model.

    Test: Router manager tests pass. Manually verified that
          router_manager_cli can still get responses from
          router_manager.

    Change-Id: I9bc8d69082dfa12894b7e640a6a65ae63477ad5c

commit 93bbf754328392f2268cfa52cffa7a90fdc9eb42
Author: Gary Bressler <geb@google.com>
Date:   Tue Jun 18 18:03:20 2019 +0000

    [appmgr] Rename uses of outgoing 'public' to 'svc'.

    This will be submitted in a breaking change along with
    https://fuchsia-review.googlesource.com/c/fuchsia/+/277254.

    Bug: CF-540
    Change-Id: I9844b6f6db337aad5fdfbb67a6c583c030c5713c

commit 6e58e7c31e0fbcf781273cccc0485496559d2e91
Author: Chris Gibson <cgibson@google.com>
Date:   Mon Jun 17 22:55:30 2019 +0000

    [router-mgr] add integration test framework

    Tests: fx run-test router_manager_cli_tests
    Change-Id: I410c67e3345f25bb947bac883d1d5d34ebdd4bb8

commit 871a7573e6a74d3cfb972ec4e7738d09163942f2
Author: Chris Gibson <cgibson@google.com>
Date:   Mon Jun 17 17:31:47 2019 +0000

    [router-mgr] add a startup log message

    Give a sign of life at runtime so we've got something to grep for in the
    logs.

    Test: built and ran, observed INFO level log message in syslog.
    Change-Id: Icee4c612097148f0922fc869c3cc0ef25747dd1c

commit b4c0b87258014677c61e72236e4b8281b7605da0
Author: Chris Gibson <cgibson@google.com>
Date:   Tue Jun 11 20:10:29 2019 +0000

    [router-mgr] fix test targets

    Fix up the test targets to have valid cmx files now that we are in
    component framework-land.

    Tests: fx run-test router_manager_tests && \
           fx run-test router_manager_cli_tests

    Change-Id: Ic0a4bb8a36737ca77a95d9ac185d4a503d4e8ee0

commit fc9d9cbab2b8a70eea77c545548c4aa7ef0387b5
Author: Chris Gibson <cgibson@google.com>
Date:   Mon Jun 10 18:05:27 2019 +0000

    [router-mgr] update to fuchsia_component

    This commit moves router_manager off the deprecated fuchsia_app
    framework and over to the new fuchsia_component model.

    Test: Router manager tests pass. Manually verified that
    router_manager_cli can still get responses from router_manager.

    Change-Id: Ieafc934b9131010617da796a803eb97218011aa0

commit 7341a5e6512586c17003d6c80d62b275f3453b07
Author: Chris Gibson <cgibson@google.com>
Date:   Mon May 13 16:56:37 2019 +0000

    [router-mgr] Get Packet Filters Support

    Parses a netfilter::Rule and turns it into a router_config::FilterRule,
    which gets passed back to the caller. Added tests for new features.

    Test: All tests pass.
    Change-Id: I996815abf74cfa24a628f8e0f54583a3bfa94e7c

commit 7b5bfa1efad637c43f0821bf3bb8adf8b1fbd8ec
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Sat May 11 00:21:29 2019 +0000

    [router-mgr] Use fuchsia.net.stack when possible

    fuchsia.netstack is deprecated, use fuchsia.net.stack For all the things
    that it provides.
    Still using fuchsia.netstack to create the bridge as that is not yet
    supported by fuchsia.net.stack

    BUG=NET-2238
    Change-Id: I6715f5bf51ba3e46fbe181b01390481b3cda8eed

commit c399b151e9ff6f5a7007db7b6ad4022b53ec3957
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Mon May 6 21:28:21 2019 +0000

    [router-mgr] Fixes failing tests.

    Change-Id: I5ed85ea9e8769efe607e44cc0f9d1fab05c21ad3

commit b96bd6ac8eedd887a90763ae8bd08e11c0797c33
Author: Chris Gibson <cgibson@google.com>
Date:   Thu May 2 19:20:46 2019 +0000

    [router-mgr] Add Packet Filtering Support

    Initial commit for configuring packet filters from Router Manager.

    Tests: Router Manager builds and runs. Tested new FilterState query with
    router_manager_cli. Additionally, ran new packet_filter tests, all pass.

    Change-Id: I43b543ed01258a3f3b2e4ade66907527d8e14d47

commit 263f6617c5d7174f98ebd90918b93c67d1a37ff7
Author: Chris Gibson <cgibson@google.com>
Date:   Thu May 2 17:34:53 2019 +0000

    [router-mgr] No longer require the futures_api

    The futures_api is no longer required, and now causes the build to fail
    when building the router product target:

    error: the feature `futures_api` has been stable since 1.36.0 and no
    longer requires an attribute to enable
     --> /ssd/fuchsia/vendor/google/bin/router_manager_cli/src/main.rs:5:38
      |
    5 | #![feature(async_await, await_macro, futures_api)]
      |                                      ^^^^^^^^^^^
      |

    Test: router_manager and router_manager_cli build again.

    Change-Id: Ib7f481db722b5d8348de94fe9ee213b31910564a

commit 67e79f5bf14553cfab4ebb485560283afbade394
Author: Taylor Cramer <cramertj@google.com>
Date:   Wed May 1 17:30:53 2019 +0000

    [rust] Remove references to legacy third_party build

    Change-Id: I5607526056ec1827c94df90ab48ab64a0e59f9f0

commit 1209b013c6992e2733b1eb373fb13d87ca30fc80
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Thu Apr 11 18:54:53 2019 -0700

    [router-mgr] Adds an error::Result type alias.

    Change-Id: Ib75b2d03ba044416d57153230fafb9e414d5dd10

commit 9bfb83946d7d1ee648e9dbc6d2480546a577eb18
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Thu Apr 25 01:35:21 2019 +0000

    [router-mgr] Configure ip addresses.

    Change-Id: I1ca95b0f7085573e19ccdbec050409ac5e5285b4

commit 31f84f8b4d9a6165c1ccef57d5f0feaa99427b7d
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Thu Apr 25 00:43:34 2019 +0000

    [router-mgr] Add support for LIF properties.

    Configures LIF properties.

    Change-Id: Idaf874211e24c43c3cd2168244493afd241b7972

commit 7c55520030b36ec01ddb1c4619397306240368e9
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Tue Apr 23 10:49:54 2019 -0700

    [router-mgr] Fix failing tests.

    Fixed tests that were not passing.
    Ignoring a test for which the code is not commited.
    Removed calls to unwrap.

    Change-Id: I21023cd45dfd0921738817f8af60ae3a96a3dab8

commit e310d4be7d225a9405f8d17b0de8aad4e92acada
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Wed Apr 24 21:20:06 2019 +0000

    [router-mgr] respond with unimplemented error.

    Return unimplemented error for thos commands that have not yet been
    implemented.

    Change-Id: Iffb4aea73014cd08ca802362ec64230521714253

commit 0793dc724c8a3a587613c0a310798dc1ab181ddf
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Mon Apr 22 17:19:25 2019 -0700

    [sdk] Move fuchsia.router.config to //sdk/fidl

    Moving router manager fidl to proper location.

    Change-Id: Ida168e65f212891e45d5fffffd93a6eeee81aede

commit f29caab42adc14d1826e9e8aadf83f9ae8691036
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Wed Mar 6 15:28:21 2019 -0800

    [router-mgr] passing errors back to client.

    Change-Id: Ibeddece25e84e6f03ece38ba9dc4eb500181535e

commit 3baa75aeb2a5cebba5ed0dbf86725741c9f6f6de
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Thu Feb 28 09:43:03 2019 -0800

    [router-mgr] Router manager able to get state and create bridge.

    Router manager reads current state (existing interfaces)
    and uses that to populate its initial state.
    It can also create bridge interfaces if indicated to do so from the
    FIDL API.

    Change-Id: Ie4a54e34ebedbb8e069bac35f877ccb354713b2c

commit 88bcb30d6a6ea5158223dd1e4b14d72f30d83be0
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Mon Apr 15 21:53:06 2019 +0000

    [router-mgr] Refactor router manager

    It refactors router manager, adds LIF and Port manager, adds unit tests.

    Change-Id: I99c489fdc9b260f394d430c687c880fc64f29046

commit 7145628173ff9f1fd37fff4edb03c6cd70f2fc04
Author: Arjun <guzt@google.com>
Date:   Fri Apr 12 21:11:50 2019 +0000

    [router_manager][overnet] Add overnet support to router manager

    Change-Id: I1ffbe504c62b5ef4b205c8ee1d6830f14330325d

commit 80fadbbc2e595f93341f1ebbb21981a36160c952
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Wed Feb 27 17:06:14 2019 -0800

    [router-mgr] Adding router_manager package

    router_manager handles router configuration through FIDL
    interfaces.

    Change-Id: I61969e96b68f91d63d5c3bd93d1a6f66a5f05305

Change-Id: Ice69aa297a4dcf7a06b0ad55eaa2b3e350d79318