[qemu][testing] Print stderr if qemu logging is going to panic
Locally without TUN configured, this outputs:

  === RUN   TestNetsvcAllFeatures
  Checking for QEMU boot...
  qemu-system-x86_64: could not configure /dev/net/tun (qemu): Operation not permitted
  --- FAIL: TestNetsvcAllFeatures (0.67s)
  panic: EOF [recovered]
	  panic: EOF

whereas previously it was just an unhelpful

  panic: EOF
  ...

This is speculative for the linked bug to attempt to point at a root
cause.

Bug: 43531
Change-Id: Id1319a6a3dd4128ade0a88adca8b4ec8af8d921e