[zircon] Add required c++ headers
An upstream change in clang may have moved some libc++ headers, leading
to some missing function names (mostly `error: no member named 'move' in
namespace 'std'`). This includes headers for functions where they are
needed.

Change-Id: I1a33f12f098d444dbf30bdba670acd57eaf6a766
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/548498
Reviewed-by: Petr Hosek <phosek@google.com>
Reviewed-by: Roland McGrath <mcgrathr@google.com>
API-Review: Roland McGrath <mcgrathr@google.com>
Commit-Queue: Leonard Chan <leonardchan@google.com>