[router-manager] Moves router-manager-cli from /vendor/google
That includes the following commits in /vendor/google repo:

commit 5719ccf24381ba5361e9471167db22439ef13994
Author: Chris Gibson <cgibson@google.com>
Date:   Fri Aug 2 00:56:35 2019 +0000

    [router-mgr] add interface to integration test

    This patchset adds an ethernet interface to the sandboxed netstack
    environment. Extended the "show ports" test to verify that
    router_manager actually detects the new interface.

    Tests: Ran router_manager_cli integration tests.

    Change-Id: Ide801c883b3ea5e3ca3e1605e57c903cacdc3dd8

commit c126143f702bcc6165144a28aca2f4610cb70c6e
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Thu Aug 1 21:24:42 2019 +0000

    [router-manager-cli] sorts show commands output.

    show ports sorts ports by topological path.
    The rest of the show commands sort by uuid.

    Change-Id: I2e16993d3852ee0035cdb9aa967b42f346f973ea

commit fff596e0a3338929282c2a94b95ae02fac63d584
Author: Wesley Aptekar-Cassels <wesleyac@google.com>
Date:   Fri Jul 19 16:35:01 2019 +0000

    [router_manager_cli] Add new networking APIs to service list

    Change-Id: Id4bf272ba7eb49111608dda82bfb1ab4533a2929

commit c1bc611e6c1a1103b9444a7d339b331eb694949e
Author: Chris Gibson <cgibson@google.com>
Date:   Wed Jul 17 19:47:47 2019 +0000

    [router-mgr] support more fidl transforms

    This patchset adds support for more fidl transforms. We can now convert
    from `router_config::FilterRule` to `netfilter::Rule`. This allows us
    to handle a new class of API requests, such as being able to add packet
    filter rules.

    Also adds a new integration test that exercises adding a new packet
    filter rule.

    Test: Builds, runs, and all tests pass.
    Change-Id: I01d73622c59bb394177e7b0294c9b28e4c963fe5

commit 6f85ce6381a9db490271f8f360f56ec81b67b6bf
Author: Ambre Williams <ambre@google.com>
Date:   Wed Jul 3 10:20:03 2019 +0000

    [fuchsia-async] prepare migration of .after_now() to DurationExt

    Stop using zx::Duration::after_now() and use fasync::Time::after(),
    that is currently an alias of zx::Time::after(). This will preserve
    source compatibility while we switch from zx::Time to fasync::Time.

    Change-Id: I84c432d4aada61d8ffc2178cc18899efe2e0f9cb

commit 5d648c1e6d100df6ecea63ba76099fc4a68af61e
Author: Chris Gibson <cgibson@google.com>
Date:   Thu Jun 20 17:21:30 2019 +0000

    [router-mgr] support test data config structs

    This commit adds support for reading CLI commands from a struct that can
    be used to test the expected output from the router_manager to the
    router_manager_cli.

    Test: fx run-test router_manager_cli_tests
    Bug: CONN-90 #done

    Change-Id: Ieb9d7668af415f95f767818e1d4068aa31e9635d

commit 9ca24a637579b202eac275ea9413378629e4fcd6
Author: Chris Gibson <cgibson@google.com>
Date:   Mon Jun 17 22:55:30 2019 +0000

    [router-mgr] add integration test framework

    Tests: fx run-test router_manager_cli_tests
    Change-Id: I410c67e3345f25bb947bac883d1d5d34ebdd4bb8

commit b84052d0aec3eb022df8ac3df80823410f8f66ac
Author: Chris Gibson <cgibson@google.com>
Date:   Tue Jun 11 20:10:29 2019 +0000

    [router-mgr] fix test targets

    Fix up the test targets to have valid cmx files now that we are in
    component framework-land.

    Tests: fx run-test router_manager_tests && \
           fx run-test router_manager_cli_tests

    Change-Id: Ic0a4bb8a36737ca77a95d9ac185d4a503d4e8ee0

commit d4c23c6cee45add77226ba496bcd06964649a082
Author: Chris Gibson <cgibson@google.com>
Date:   Fri Jun 7 01:22:28 2019 +0000

    [router-mgr] Redirect output to stdout or buffer

    Rust's test runner internally redirects stdout during test runs making
    stdout be not capturable via file descriptor redirection. Instead, we
    create a new Printer object, given a template parameter it can write
    either to stdout or an in-memory buffer.

    This commit also adds a `router_manager_cli_tests` target to the
    build and tests that writing to a buffer succeeds.

    TEST: Builds, runs, and all tests pass.
    BUG: CONN-90
    Change-Id: I1b8adedf213fad3de190a46d12d62a380b3ba4fd

commit 8ead5b3823b0d30c816f3e1a13f73291011f0962
Author: enlightened <enlightened@google.com>
Date:   Thu Jun 6 04:33:31 2019 +0000

    [router-manager-cli] most complete version of CLI

    Implements most of the commands for the router amanger cli. This is a
    prototype for router manager cli, which includes most of the commands
    supported by the cli. Changes include additional subcommands, additional
    help messages and implementation of FIDL call for most commands. Also
    added a test package.

    Change-Id: I4fd52ec9385b91887df3cf6f38e97e3fb4c847f8

commit ced344c04d2ea24d8ed319d7a11da405ab0f22d2
Author: Chris Gibson <cgibson@google.com>
Date:   Thu May 2 19:20:46 2019 +0000

    [router-mgr] Add Packet Filtering Support

    Initial commit for configuring packet filters from Router Manager.

    Tests: Router Manager builds and runs. Tested new FilterState query with
    router_manager_cli. Additionally, ran new packet_filter tests, all pass.

    Change-Id: I43b543ed01258a3f3b2e4ade66907527d8e14d47

commit 28a1c12991d7d0144280777f9e6506d72df4fbe5
Author: Chris Gibson <cgibson@google.com>
Date:   Thu May 2 17:34:53 2019 +0000

    [router-mgr] No longer require the futures_api

    The futures_api is no longer required, and now causes the build to fail
    when building the router product target:

    error: the feature `futures_api` has been stable since 1.36.0 and no
    longer requires an attribute to enable
     --> /ssd/fuchsia/vendor/google/bin/router_manager_cli/src/main.rs:5:38
      |
    5 | #![feature(async_await, await_macro, futures_api)]
      |                                      ^^^^^^^^^^^
      |

    Test: router_manager and router_manager_cli build again.

    Change-Id: Ib7f481db722b5d8348de94fe9ee213b31910564a

commit 0fd8dee41ffa151cbe2c88f37b4c35d6e5f6d543
Author: Taylor Cramer <cramertj@google.com>
Date:   Wed May 1 17:30:53 2019 +0000

    [rust] Remove references to legacy third_party build

    Change-Id: I5607526056ec1827c94df90ab48ab64a0e59f9f0

commit 73c58299d1a0bbdea00fe74febeb5235eb29fa58
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Mon Apr 22 17:19:25 2019 -0700

    [sdk] Move fuchsia.router.config to //sdk/fidl

    Moving router manager fidl to proper location.

    Change-Id: Ida168e65f212891e45d5fffffd93a6eeee81aede

commit 34f57fd72d6c0a51c41dd538bdfbb083aefb867b
Author: Arjun <guzt@google.com>
Date:   Mon Apr 22 18:28:11 2019 +0000

    [router_manager][cli][overnet] Add overnet support to router manager cli

    Change-Id: Iedf78501d7fce1377a09dde60005e960616b7469

commit 7b3fba22bf43d2d7c04f61cdac0b2ef49d90bc3a
Author: Chris Gibson <cgibson@google.com>
Date:   Thu Apr 18 19:56:54 2019 +0000

    [router_manager] router_manager_cli shell command

    Currently invoking router_manager_cli needs the complete fuchsia
    component url. This commit makes router_manager_cli be a shell
    command instead, foregoing the use of the `run` command.

    Test: fx shell router_manager_cli help

    USAGE:
        router_manager_cli <SUBCOMMAND>

    FLAGS:
        -h, --help       Prints help information
        -V, --version    Prints version information

    SUBCOMMANDS:
        add
        help    Prints this message or the help of the given subcommand(s)
        list
        set
        show

    Change-Id: I7b4acb13d02e3dfee538b2259749918b50c1d0ff

commit e96e0bbcdd0cb17cf4301643055f40f7aa726472
Author: Daniel Pradilla <dpradilla@google.com>
Date:   Thu Apr 11 00:01:47 2019 +0000

    [router-mgr] Adding router_manager_cli package to toulouse.

    Change-Id: Id5accef27b88fd791bba92dda793fdd77f7f72f5

Change-Id: I643c89a7e419085d298fad1a537089a6ffa6dcb6