Revert "[kernel][vdso] Sanity-check the vDSO image matches the kernel"
This reverts commit f4bb364fa4963a45cb977a3910dfe05f80cf6bd0.

Reason for revert: This seems to break the QEMU full build.

../../zircon/kernel/lib/userabi/vdso.cc:196:46: error: invalid suffix 'x' on integer constant
constexpr VdsoBuildIdNote kVdsoBuildIdNote = VDSO_BUILD_ID_NOTE_BYTES;
                                             ^
kernel-x64-clang/gen/kernel/lib/userabi/vdso-code.h:8:180: note: expanded from macro 'VDSO_BUILD_ID_NOTE_BYTES'
#define VDSO_BUILD_ID_NOTE_BYTES {0x04, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x47, 0x4e, 0x55, 0x00, 0x2b, 0x81, 0x44, 0x7c, 0x72, 0x20, 0xa0, 0x13, 0x+., 0xD|, 0xr, 0x,}
                                                                                                                                                                                   ^
../../zircon/kernel/lib/userabi/vdso.cc:196:46: error: expected expression
kernel-x64-clang/gen/kernel/lib/userabi/vdso-code.h:8:182: note: expanded from macro 'VDSO_BUILD_ID_NOTE_BYTES'
#define VDSO_BUILD_ID_NOTE_BYTES {0x04, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x47, 0x4e, 0x55, 0x00, 0x2b, 0x81, 0x44, 0x7c, 0x72, 0x20, 0xa0, 0x13, 0x+., 0xD|, 0xr, 0x,}


Original change's description:
> [kernel][vdso] Sanity-check the vDSO image matches the kernel
> 
> Extract the build ID note contents at build time and embed that
> separately in the kernel so it can verify at runtime that it
> matches the vDSO image.  The kernel bakes in expectations about
> the exact instruction sequences that appear in the vDSO, so it's
> crucial that it always be the precise vDSO image that the kernel
> was built for.  The image is pasted into the kernel binary at
> build time today, but in the future it will be packed differently
> where accidental mismatches will become possible if the wrong ZBI
> repacking shenanigans are done.
> 
> Test: change consists of adding an assert on the boot path
> Change-Id: I61cdc42302fd11f09f7ffd2aa4e0a1ac04369a81
> Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/383644
> Commit-Queue: Roland McGrath <mcgrathr@google.com>
> Reviewed-by: George Kulakowski <kulakowski@google.com>
> Testability-Review: Roland McGrath <mcgrathr@google.com>

TBR=kulakowski@google.com,travisg@google.com,phosek@google.com,mcgrathr@google.com,maniscalco@google.com,joshuaseaton@google.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Change-Id: Ic0c319e570161bf5cd3277f7fc68bc2b5946630e
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/391382
Reviewed-by: Fady Samuel <fsamuel@google.com>
Commit-Queue: Fady Samuel <fsamuel@google.com>