[input] Revert "Add keymap size constant; const keymaps"
This reverts commit 24b9af560cac6e5ed12edf0dbdfe00d0f7fbc420.

Reason for revert: Unnecessary hard transition.

Original change's description:
> [input] Add keymap size constant; const keymaps
> 
> This is to support https://fuchsia-review.googlesource.com/224012.
> 
> Test: virtcon physical keyboard input
>       device shell physical keyboard input
>       device shell IME input
>       built with excess elements in keymap:
>         system/ulib/hid/keymaps.c:111:45: error: excess elements in array
> 	  initializer [-Werror]
> 
> Change-Id: I353478532a91e2959ad897cb0635d47f844bc4c1

TBR=tkilbourn@google.com,rosswang@google.com,jaeheon@google.com

Change-Id: I52744285281fda6b185e291b6881c6731bd346d9
No-Presubmit: true
No-Tree-Checks: true
No-Try: true