[fxfs] Add static assertion for versioned_type! with version too large.
This generates `static_assertions::const_assert!()` from the
versioned_type macro to check that the supplied version mapping
doesn't exceed LATEST_VERSION.

It should be trivial to extend this to check the lowest supported
version once we have code for that landed.

The errors are a bit unfortunate, but static_assertions doesn't support user-supplied error messages...
```
error[E0080]: evaluation of constant value failed  --> ../../src/storage/fxfs/src/serialized_types/types.rs:48:1
48 | / versioned_type! {
49 | |     19.. => StoreInfo,
50 | |     17.. => StoreInfo,
51 | |     8.. => StoreInfoV1,
52 | | }
   | |_^ attempt to compute `0_usize - 1_usize`, which would overflow
```

Change-Id: I5781e100e70ae37fa67c613936ab855d1edaddc8
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/679329
Reviewed-by: Chris Suter <csuter@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Fuchsia-Auto-Submit: Aaron Drew <ripper@google.com>