[rust][LSC] Prepare for Rust toolchain roll
Changes:

[banjo] Specify #[repr(C)] for packed structs

`#[repr(packed)]` does not imply `#[repr(C)]`, but we were generating
code as if it did. This was caught by a warning in a newer version of
rustc.

Ref: https://doc.rust-lang.org/reference/type-layout.html#the-alignment-modifiers
Originally: I7c0c920452e915baefc1dc97e99a50c27298ebf1

[fuchsia-inspect] Fix macro hygiene violation

As best as I can tell, this was only allowed to compile because of a bug
in rustc that has now been fixed in a newer version.

The problem was that writing `value.as_bytes()` in a macro invocation
like this, where `value` is a name generated by the macro itself,
violates the hygiene rule that you can't "accidentally" name values
created in a macro from outside or vice versa. This now manifests as the
following error:

error[E0425]: cannot find value `value` in this scope
  --> src/lib.rs:24:24
   |
24 | property!(String, str, value.as_bytes());
   |                        ^^^^^ not found in this scope

Originally: Ieb3dd3b751fb52599c542f8ef70020dc6fd637a0

[rust][wasm] Remove extern "C" from wasm example

Newer Rust compilers don't permit Option or String in extern "C"
functions because they aren't FFI safe.

Originally: I34589ad0fbe32f87b3d8adcd781c303dba17e075

[rust][netstack][LSC] Update specialization code to work on newer rustc

rustc no longer lets you get away without implementing associated trait
bounds on defaulted associated types, so I had to implement those.

Bug: 48578
Originally: Ia14f1283347746403bf4636517b300d9c77135d1

Bug: 55782
Change-Id: Ie5d7be347415f4aa7eb96367903a904cec332d49
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/411040
Reviewed-by: Didrik Nordstrom <dnordstrom@google.com>
Testability-Review: Didrik Nordstrom <dnordstrom@google.com>
Commit-Queue: Tyler Mandry <tmandry@google.com>