[build] Suppress -Wunused-but-set-variable in grpc
This patch suppresses -Wunused-but-set-variable warning in
grpc third party code that does not comply with.

The code that causes the issue is as the following:
third_party/grpc/src/core/ext/filters/client_channel/lb_policy/weighted_target/weighted_target.cc:326:10:
error: variable 'num_transient_failures' set but not used

Bug: 96410
Change-Id: I43cb554d405cb5307511fd0f6d9a38bd13b8bda2
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/664068
Fuchsia-Auto-Submit: Gulfem Savrun Yeniceri <gulfem@google.com>
Reviewed-by: Jay Zhuang <jayzhuang@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>