Revert "[fit] Add a fit::callback "run once" variant of fit::function"
This reverts commit bfed6f5ca5cd6150dc339c3b0984c6470b4bd0fc.

Reason for revert: On Thu, May 2, 2019 at 10:24 AM <...> wrote:
This change broke compile step in chromium with this error:
In file included from ../../third_party/fuchsia-sdk/sdk/pkg/fit/inclu
de/lib/fit/function.h:8:
../../third_party/fuchsia-sdk/sdk/pkg/fit/include/lib/fit/function_internal.h:183:63: error: declaration shadows a static data member of 'target<type-parameter-0-0, false, true, type-parameter-0-1, type-parameter-0-2...>' [-Werror,-Wshadow]
    static const void* target_type_id(void* bits, const void* ops) {
                                                              ^
../../third_party/fuchsia-sdk/sdk/pkg/fit/include/lib/fit/function_internal.h:209:46: note: previous declaration is here
    static const target_ops<Result, Args...> ops;
                                             ^
1 error generated.
See https://chromium-review.googlesource.com/c/chromium/src/+/1592429
I'm guessing this happens because chromium compiles this code as C++14 instead of C++17

Original change's description:
> [fit] Add a fit::callback "run once" variant of fit::function
> 
> To address fxb/ZX-3616
> 
> Test: fit-test
> Change-Id: I85d6454a07dd4a1578f608a6bac8f56b98b12a6d

TBR=jeffbrown@google.com,abarth@google.com,eieio@google.com,richkadel@google.com

Change-Id: Ic532538f11050e98aa5618ecb1f0e789d994b867
No-Presubmit: true
No-Tree-Checks: true
No-Try: true