[revert][check-licenses] Add new golden patterns for notice changes
This reverts commit b9e917178a09a2d34d0162fe1ab0613205403e70.

Reason for revert: This seems to be causing failures on some try runs with the output:

=== RUN   TestPatternsMatchExamples
LENGTH 97    golden_test.go:69: TestPatternsMatchExamples, got open host_x64/gen/tools/check-licenses/golden/examples/notice/bsd/fuchsia_bsd2.txt: no such file or directory
    golden_test.go:80: TestPatternsMatchExamples, host_x64/gen/tools/check-licenses/golden/patterns/notice/bsd/fuchsia_bsd2.lic pattern doesn't match example
--- FAIL: TestPatternsMatchExamples (0.12s)
FAIL

Original change's description:
> [check-licenses] Add new golden patterns for notice changes
>
> This adds new golden patterns and examples for updates to the Fuchsia
> standard notice header.
>
> Bug: 66908
> Change-Id: Ifbb247379a0cff4efb422d8f52f699a30a0a9e92
> Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/464989
> Fuchsia-Auto-Submit: James Robinson <jamesr@google.com>
> Reviewed-by: Jerry Belton <jcecil@google.com>
> Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>

TBR=jamesr@google.com,jcecil@google.com,omerlevran@google.com,auto-submit@fuchsia-infra.iam.gserviceaccount.com

Change-Id: If01d03612dde28530db3e19caaa2c1054c39b0cd
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 66908
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/465176
Reviewed-by: James Robinson <jamesr@google.com>
Commit-Queue: James Robinson <jamesr@google.com>