[sysmem] Fix missing dependency on llcpp in tests
From:
https://ci.chromium.org/p/fuchsia/builders/try/fuchsia-host-mac-subbuild/b8879206045376978672

FAILED: obj/zircon/system/utest/sysmem/sysmem.sysmem_tests.cc.o
...
../../zircon/system/utest/sysmem/sysmem_tests.cc:8:10: fatal error: 'fuchsia/sysmem/llcpp/fidl.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

I think this often would work if that file's already built, but
depending on ordering, the header might not have been generated.

Change-Id: I6900487647094b3641f9151a3cd5a1cb10750693
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/392857
Reviewed-by: Dustin Green <dustingreen@google.com>
Commit-Queue: Scott Graham <scottmg@google.com>