[build] Add GN label to golden file error.
Helps developers fix up failures when they happen in CQ first.

Example of the new message format:

```
Error: Golden file mismatch
Please acknowledge this change by updating the golden.

You can run this command:
  cp ... ...
Or you can rebuild with `bless_goldens=true` in your GN args and
`//tools/cmx2cml/tests/goldens:button_checker_unittest` in your build graph.
```

Change-Id: I53fcf0f1c39db88942fe3cd257f3f46655943446
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/699252
Reviewed-by: Shai Barack <shayba@google.com>
Fuchsia-Auto-Submit: Adam Perry <adamperry@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>