[wlan][sme] Limit AP and Mesh channels to allow
Logics is hosted in SME.
Error message assising the users is hosted in wlantool2.
sme.fidl is augmented to support InvalidArguments and DfsUnsupported
for both ApStartResult and JoinMeshResult.
Their Error is renamed to InternalError.

Test: wlantool2 ap start 0 --ssid anyname --channel X
      For X, use 14, 35, 50, 96, 169 for invalid channel
      For X, use 50, 100, 140 for DFS channel

$ fx shell wlantool2 ap start 0 --ssid porce-ap --channel 100
Ap(Start { iface_id: 0, ssid: "porce-ap", password: None, primary_chan: 100 })
Error: InvalidArguments
$ fx shell wlantool2 ap start 0 --ssid porce-ap --channel 15
Ap(Start { iface_id: 0, ssid: "porce-ap", password: None, primary_chan: 15 })
Error: InvalidArguments
$ fx shell wlantool2 ap start 0 --ssid porce-ap --channel 11
Ap(Start { iface_id: 0, ssid: "porce-ap", password: None, primary_chan: 11 })
Success

WLAN-925 #done
WLAN-903 #comment

Change-Id: I081f394f5e8fb9c21d5d1acc8037b3ac1d542d61