Reland "[fidl] FIDL api summarization tool - initial commit"
This reverts commit 631f8518e42e19809c416e8f7ec1bf3485fd6d88.

Reason for revert: Fixed the test flakiness.  The BUILD.gn needed
a host_test_data declaration to ensure that `fidlc` is available
at test runtime.

Original change's description:
> Revert "[fidl] FIDL api summarization tool - initial commit"
>
> This reverts commit 5afbbd673ac94168034b68304800dff16d5ea8cf.
>
> Reason for revert: Flakiness when trying to find fidlc.
>
> === RUN   TestSummarize
> === RUN   TestSummarize/library_only
>     endtoendtest.go:69: fidlc stdout:
>     endtoendtest.go:70: fidlc stderr:
>     endtoendtest.go:71: fork/exec host_x64/fidlc: no such file or directory
> --- FAIL: TestSummarize (0.00s)
>     --- FAIL: TestSummarize/library_only (0.00s)
> FAIL
>
> Original change's description:
> > [fidl] FIDL api summarization tool - initial commit
> >
> > This change checks in the first code of a FIDL API summarization tool.
> > The goal of the tool is to convert a FIDL intermediate representation
> > into a mainly human-readable list of API elements exposed by the FIDL
> > API.
> >
> > Please see `README.md` for more details.
> >
> > Current status:
> >
> > - Completed a TDD test fixture for processing known examples of API
> >   summarization.
> > - Builds a data model for the API summary, which is simpler than the
> >   FIDL IR, as we anticipate to produce a machine-readable form as well.
> >
> > Bug: 67873
> > Change-Id: I930e5bf8f30bf27eed297d96c36d183a0f195053
> > Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/467454
> > Reviewed-by: Pascal Perez <pascallouis@google.com>
> > Commit-Queue: Filip Filmar <fmil@google.com>
>
> TBR=pascallouis@google.com,fmil@google.com,mkember@google.com
>
> Change-Id: Ic7958150203047f4101ca6b43abd1e38ef19abff
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 67873
> Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/475802
> Reviewed-by: Filip Filmar <fmil@google.com>
> Commit-Queue: Filip Filmar <fmil@google.com>

TBR=pascallouis@google.com,fmil@google.com,mkember@google.com

Multiply: summary_test
Bug: 67873
Change-Id: I4fbe8979acb275559816cc18f6fb7fcea36ee257
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/475858
Fuchsia-Auto-Submit: Filip Filmar <fmil@google.com>
Reviewed-by: Mitchell Kember <mkember@google.com>
Reviewed-by: Shai Barack <shayba@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>