[fx set] Fix tests
The `fx set` tests had been passing, but producing some error logs that
suggested something was failing, e.g.:

  ERROR: Build directory missing or removed. (/tmp/tmp.foo)
  ERROR: run "fx set", or specify a build dir with --dir or "fx use"

This was happening because `fx set` runs `fx-change-build-dir` after it
runs `gn gen`, and `fx-change-build-dir` expects to be passed a valid
build directory containing an `fx.config` file with some environment
variables. That file is normally generated by GN itself, but in the
tests GN is mocked out, so `fx.config` isn't present in the build
directory after running `gn gen`.

That caused `fx set` to fail in the tests, but the tests themselves
weren't failing because they didn't make assertions about the exit code
of `fx set`. They only checked that `fx set` passed the expected args to
GN, so a failure in any `fx set` step after `gn gen` would not cause the
tests to fail.

So this was a two-part fix:
1. Have the mocked-out GN executable create a `fx.config` file in the
   build directory to make `fx-change-build-dir` happy so `fx set`
   passes.
2. Wrap every `fx set` invocation in the tests in `BT_ASSERT`, so in the
   future a test will fail if `fx set` produces a non-zero exit code. I
   tested this without the fix from #1 to confirm that it does indeed
   propagate the failure.

Change-Id: I238a313b263598390ddaac0c55c4d4d16295d233
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/509818
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Fuchsia-Auto-Submit: Oliver Newman <olivernewman@google.com>
Reviewed-by: Gary Boone <gboone@google.com>