[unification] Move //zircon/system/ulib/log to the GN build
Affected libraries:
//zircon/system/ulib/log

scripts/unification/verify_element_move.py --reference local/initial.json:

Error     aux         element removed: lib/profile/liblog.so
Error     aux         element removed: lib/ubsan/liblog.so
Error     aux         element removed: lib/asan-ubsan/liblog.so
Error     aux         element removed: test/sys/libc-test
Error     aux         element removed: lib/ubsan-sancov-full/liblog.so
Error     aux         element removed: lib/sancov/liblog.so
Error     aux         element removed: lib/ubsan-sancov/liblog.so
Error     aux         element removed: lib/asan/liblog.so
Error     aux         element added: lib/ubsan/libinspector.so
Error     aux         element added: lib/asan/libinspector.so
Error     aux         element added: lib/profile/libinspector.so
Error     aux         element added: lib/sancov/libinspector.so
Error     aux         element added: test/sys/mmio-ptr-unittest-test
Error     aux         element added: lib/asan-ubsan/libinspector.so
Error     aux         element added: lib/ubsan-sancov/libinspector.so
Error     aux         element added: lib/ubsan-sancov-full/libinspector.so
Warning   aux         size change for lib/profile/libfdio.so: -1% (10.8M)
Warning   aux         size change for lib/libinspector.so: -2% (112.0K)
Warning   aux         size change for test/fs/blobfs-unit-test: -1% (2.1M)
Error     aux         size change for test/sys/stdio-test: +4% (88.0K)
Error     aux         size change for lib/liblog.so: +11% (13.4K)
Error     aux         size change for test/sys/fit-test: +2% (828.5K)
Error     aux         size change for test/sys/dma-buffer-test: +6% (64.0K)
Warning   aux         size change for test/sys/sysmem-test: -3% (368.0K)
Warning   aux         size change for test/ddk/fshost-test-test: -1% (412.0K)
Warning   image       size change for driver/sysmem.so: -2% (237.8K)
Error     image       size change for driver/hid.so: -17% (121.8K)
Warning   image       size change for lib/libinspector.so: -2% (112.0K)
Error     image       shared library removed from driver/hid.so: libasync-default.so
Error     tests       element removed: test/sys/libc-test
Error     tests       element added: test/sys/mmio-ptr-unittest-test
Error     tests       size change for test/sys/fit-test: +2% (828.5K)
Warning   tests       size change for lib/libinspector.so: -2% (112.0K)
Warning   tests       size change for test/sys/sysmem-test: -3% (368.0K)
Warning   tests       size change for test/fs/blobfs-unit-test: -1% (2.1M)
Error     tests       size change for test/sys/stdio-test: +4% (88.0K)
Error     tests       size change for lib/liblog.so: +11% (13.4K)
Error     tests       size change for test/sys/dma-buffer-test: +6% (64.0K)
Warning   tests       size change for test/ddk/fshost-test-test: -1% (412.0K)
Error: summaries do not match!

Generated with //scripts/unification/move_cpp_library.py

Bug: 36548
Change-Id: I9d16c9a7888013cd563be13bb4614a84cd09133d
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/389330
Commit-Queue: Theodore Dubois <tbodt@google.com>
Reviewed-by: P.Y. Laligand <pylaligand@google.com>