[fint] Parse ninja stderr in addition to stdout
In https://fxrev.dev/508299 I incorrectly assumed that ninja's "ninja:
error: ..." output logs were printed to stdout along with the status
logs like "[1/12345] STAMP ...". However, it turns out that the "ninja:
error: ..." logs are actually printed to stderr, which is why "ninja:
error" failures weren't getting parsed correctly, e.g.:
https://ci.chromium.org/b/8850337454975083648. So we need to update the
ninja output parser to check stderr as well as stdout.

Ideally there would be separate parsers for stdout and stderr, because
each type of log should consistently be printed to either stdout or
stderr, but it's simplest to just use the same parser struct to handle
both stdout and stderr.

Bug: 67861
Change-Id: I1832f6cd0e9e181e90da3c65c056f1c500422bac
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/514301
Reviewed-by: Ina Huh <ihuh@google.com>
Commit-Queue: Oliver Newman <olivernewman@google.com>
Fuchsia-Auto-Submit: Oliver Newman <olivernewman@google.com>