[cobalt] Remove the old memory dimension that no longer exists.
The memory dimension was removed in
https://cobalt-analytics-review.googlesource.com/c/config/+/6800

This change is failing to roll due to the build failure:

[42850/63886] CXX obj/src/cobalt/bin/system-metrics/system_metrics_daemon_lib.system_metrics_daemon.cc.o
FAILED: obj/src/cobalt/bin/system-metrics/system_metrics_daemon_lib.system_metrics_daemon.cc.o
/b/s/w/ir/cache/goma/client/gomacc  ../../prebuilt/third_party/clang/linux-x64/bin/clang++ -MD -MF obj/src/cobalt/bin/system-metrics/system_metrics_daemon_lib.system_metrics_daemon.cc.o.d -DTOOLCHAIN_VERSION=699na4cdUtw5x7ni5F6yiSpQlUubO5Z9Gn6wxS0jGMcC -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -DNDEBUG=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -I../.. -Igen -I../../garnet/public -I../../peridot/public -I../../topaz/public -Igen/garnet/public -Igen/peridot/public -Igen/topaz/public -I../../zircon/system/ulib/syslog/include -Ifidling/gen/sdk/fidl/fuchsia.ui.activity -I../../zircon/system/ulib/fidl/include -I../../sdk -Igen/sdk -I../../zircon/system/ulib/fit/include -I../../zircon/system/ulib/fidl-async/include -I../../zircon/system/ulib/zx/include -I../../zircon/system/ulib/fidl/include -I../../zircon/system/ulib/async/include -I../../zircon/system/ulib/async/include -Ifidling/gen/sdk/fidl/fuchsia.sys -Ifidling/gen/zircon/system/fidl/fuchsia-mem -Ifidling/gen/zircon/system/fidl/fuchsia-io -I../../zircon/system/ulib/fdio/include -I../../zircon/system/ulib/async/include -Ifidling/gen/src/sys/timekeeper -Ifidling/gen/zircon/system/fidl/fuchsia-cobalt -I../../zircon/system/ulib/fbl/include -I../../zircon/system/ulib/fzl/include -Ifidling/gen/zircon/system/fidl/fuchsia-io -Ifidling/gen/zircon/system/fidl/fuchsia-mem -I../../third_party/cobalt -Igen/third_party/cobalt -I../../garnet/public/lib/syslog/cpp -I../../zircon/system/ulib/syslog/include -I../../third_party/protobuf/src -Igen -I../../third_party/protobuf/src -I../../zircon/system/ulib/async-loop/include -I../../zircon/system/ulib/async-loop/include -I../../zircon/system/ulib/async-loop/include -I../../zircon/system/ulib/trace/include -I../../zircon/system/ulib/trace-engine/include -I../../zircon/system/ulib/trace-provider/include -Ifidling/gen/zircon/system/fidl/fuchsia-hardware-thermal -Ifidling/gen/zircon/system/fidl/fuchsia-hardware-thermal -Ifidling/gen/zircon/system/fidl/fuchsia-kernel -Ifidling/gen/zircon/system/fidl/fuchsia-mem -I../../zircon/system/ulib/fidl/include -fcolor-diagnostics -fcrash-diagnostics-dir=clang-crashreports -idirafter ../../zircon/system/public -idirafter ../../zircon/system/ulib/zircon/include -idirafter ../../zircon/third_party/ulib/musl/include -idirafter ../../zircon/system/ulib/zircon/include -idirafter ../default.zircon/user.vdso-x64-clang.shlib/gen --target=x86_64-fuchsia -march=x86-64 -mcx16 -fdebug-prefix-map=/b/s/w/ir/k/fuchsia/=../../ -no-canonical-prefixes -fomit-frame-pointer -g3 -Wall -Wextra -Wnewline-eof -Wno-unused-parameter -Wno-unknown-warning-option -Wno-unknown-warning-option -Wno-c99-designator -Wno-int-in-bool-context -Wno-address-of-packed-member -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -ftrivial-auto-var-init=pattern -Wthread-safety -Werror -Wno-error=deprecated-declarations -fvisibility-inlines-hidden -std=c++17 -Wno-deprecated-copy -fno-exceptions -fno-rtti -c ../../src/cobalt/bin/system-metrics/system_metrics_daemon.cc -o obj/src/cobalt/bin/system-metrics/system_metrics_daemon_lib.system_metrics_daemon.cc.o
../../src/cobalt/bin/system-metrics/system_metrics_daemon.cc:47:29: error: no type named 'FuchsiaMemoryExperimental2MetricDimensionTimeSinceBoot' in namespace 'fuchsia_system_metrics'
    fuchsia_system_metrics::FuchsiaMemoryExperimental2MetricDimensionTimeSinceBoot;
    ~~~~~~~~~~~~~~~~~~~~~~~~^
1 error generated.

Change-Id: If3d34710ebe9c3bb78aa7b805c806e00bb639797