[unification] Move //zircon/system/utest/logger to the GN build
Generated with: //scripts/unification/move_zn_element.py

scripts/unification/verify_element_move.py --reference local/initial.json:

Warning   aux         size change for test/sys/logger-test: -6% (72.0K)
Error     aux         shared library added to test/sys/logger-test: libtrace-engine.so
Warning   tests       size change for test/sys/logger-test: -6% (72.0K)
Error     tests       shared library added to test/sys/logger-test: libtrace-engine.so
Error: summaries do not match!

The path to this is:

$ fx gn path out/default //zircon/system/utest/logger //zircon/public/lib/trace-engine
//zircon/system/utest/logger:logger --[private]-->
//zircon/public/lib/logger:logger --[public]-->
//zircon/public/lib/svc:svc --[public]-->
//zircon/public/lib/fs:fs --[public]-->
//zircon/public/lib/trace:trace --[public]-->
//zircon/public/lib/trace-engine:trace-engine

In all cases, logger -> svc and svc -> fs are both :headers, but in the
GN migration, these are ignored, so we get an actual dependency:
See: https://fuchsia.googlesource.com/fuchsia/+/master/zircon/public/gn/BUILDCONFIG.gn#515

Bug: 36139
Change-Id: I8cf61bc82d1633e699a998f85897026f72735f7c