[fit] Revert two recent sequencer changes
Revert "[fit] Rename sequential_executor to single_threaded_executor."
Revert "[fit] Add fit::sequencer for ensuring sequential execution order."

This reverts commit abf79d3302a57378233377a328c891a6deed968b.
This reverts commit 7baf23bcf61351ddc9965a0fdc656a9298b5a221.

This code does not build, at least as C++14:

In file included from headers/headers.cc:98:
.../pkg/fit/_virtual_includes/fit/lib/fit/sequencer.h:47:14: error: use
of class template 'fit::bridge' requires template arguments
        fit::bridge bridge;

Test: Failed SDK builders
Change-Id: I95ff20ee448faea541ce7526ad139bbaf9449809