[audio_core] Zero-phase Point sampler
The SampleAndHold resampler (PointSampler) has been changed
to a proper nearest-neigbor selector, making it flat-phase
like its Linear and WindowedSinc companions.

The AudioResult values for PointSampler have been updated to
match: minor changes in frequency response, SINAD and out-of
-band rejection. Phase response is now ZERO, with one
exception: 1:2 upsampling still has linear phase shift,
because at exactly halfway between two samples, we choose
one (the next, not the previous) rather than averaging them.
(Averaging would make us truly zero-phase at all resampling
ratios, but would further roll-off high-frequencies.)

This resampler manages timestamps appropriately, but to
properly integrate it into a delay-compensated audio
pipeline we should regard it as requiring one additional
audio frame of lead time from upstream parties.

Test: existing Phase Response cases (audio_fidelity_tests)
clearly show the improvement

Fixed: 49400

Change-Id: I5f41fcd5761ddfd808bb7feb951460c6275e211b
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/377216
Commit-Queue: Martin Puryear <mpuryear@google.com>
Reviewed-by: Tim Detwiler <tjdetwiler@google.com>
Testability-Review: Tim Detwiler <tjdetwiler@google.com>