[libc] add MODULE_LDFLAGS += --no-undefined-version
Add --no-undefined-version to the linker command line. Undefined symbols
in the exported.map file will now be a compiler error. This makes the
map file more robust against changes in libc.

An attempt to introduce an undefined symbol in the map file will
generate an error similar to:

  ./prebuilt/downloads/x86_64-elf-6.3.0-Linux-x86_64/bin/x86_64-elf-ld.gold:
  error: version script assignment of  to symbol asdfasdfass failed:
  symbol not defined
  make[1]: ***
  [/work/fuchsia/topaz/out/build-zircon/build-user-x86-64/system/ulib/c/libc.so]
  Error 1

Change-Id: Ic1cd9cb00ebbc3b28a2ebdd812685edb8c7f63c4