[build] Suppress -Wunused-but-set-variable in zstd
This patch suppresses -Wunused-but-set-variable warning in
zstd third party code that does not comply with.

The code that causes the issues is as the following:
third_party/zstd/src/lib/compress/zstd_compress_superblock.c:412:12:
error: variable 'litLengthSum' set but not used

Bug: 77973
Change-Id: Id6e37aaa1bdd51cc1dfcc39842ff4fbcfae1a1e0
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/550732
Commit-Queue: Gulfem Savrun Yeniceri <gulfem@google.com>
Reviewed-by: Shai Barack <shayba@google.com>