[Ermine] Wrapped the state change in action
Fixed the issue that all launching apps throw the following error:

ERROR: 'package:mobx/src/core/context.dart': Failed assertion: line 220 pos 18: '_state.isWithinBatch': Side effects like changing state are not allowed at this point. Please wrap the code in an "action". Tried to modify: Observable@9

Change-Id: Idf6bb4e8fe53f2a8df03ae159417607b7595b5d4
Reviewed-on: https://fuchsia-review.googlesource.com/c/experiences/+/573121
Commit-Queue: Yeonhee Lee <yhlee@google.com>
Reviewed-by: Sanjay Chouksey <sanjayc@google.com>