[fidl][llcpp] Reland "Fix sending empty tables"
This reverts commit f9e5e4bde97922f5a00d9cfbcabca89a583fbcd4.

Reason for revert: reland CL

Original change's description:
> Revert "[fidl][llcpp] Fix sending empty tables"
>
> This reverts commit 2bee54485abdfd9b73f567f8039e686025cb5bc4.
>
> Reason for revert:
> ethernet/gen/llcpp/include/fuchsia/hardware/ethernet/llcpp/fidl.h:8:
> ../../zircon/system/ulib/fidl/include/lib/fidl/llcpp/coding.h:195:27: error: no member named 'HasPointer' in 'llcpp::fuchsia::hardware::ethernet::Device::SetClientNameRequest'
>   static_assert(FidlType::HasPointer, "Only types with out-of-line members need linearization");
>                 ~~~~~~~~~~^
>
> Original change's description:
> > [fidl][llcpp] Fix sending empty tables
> >
> > We would expect that the
> > https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=40782#c6 idea of
> > using some valid pointer value in the table vector header would work,
> > since it appeases the linearizer. However, it turned out that
> > empty tables don't go through linearization, going straight to the
> > encoder which would fail. They don't get linearized because their
> > max-out-of-line value as inferred by the compiler is zero, because
> > the maximum number of elements is zero. LLCPP then assumes that
> > this structure doesn't have pointers, and don't apply
> > linearization.
> >
> > We could add another type shape visitor that outputs if the
> > message has a pointer, and use that to determine running
> > linearization. I found the message depth property nicely describes
> > if the message has a pointer. This CL switches the
> > linearization criterion to that, and have the linearizer handle
> > the absent vector case.
> >
> > Fixed: 40782
> >
> > Change-Id: Iff5c8131c3636fb1628229d3bf31eb0cb2533802
>
> TBR=ianloic@google.com,pascallouis@google.com,yifeit@google.com,fcz@google.com,mkember@google.com
>
> Change-Id: Ia605296a9fa4d78625714b9bd8944811ebd7cde4
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true

TBR=ianloic@google.com,scottmg@google.com,pascallouis@google.com,yifeit@google.com,fcz@google.com,mkember@google.com

Change-Id: I018af265e01b3efcbc3792f878098808b2fdcc76