[unification] Move //zircon/system/ulib/zircon-crypto to the GN build
Affected libraries:
//zircon/system/ulib/zircon-crypto

scripts/unification/verify_element_move.py --reference local/initial.json:

Error     aux         element removed: lib/ubsan/libzircon-crypto.so
Error     aux         element removed: lib/profile/libzircon-crypto.so
Error     aux         element removed: lib/ubsan-sancov-full/libzircon-crypto.so
Error     aux         element removed: lib/asan-ubsan/libzircon-crypto.so
Error     aux         element removed: lib/ubsan-sancov/libzircon-crypto.so
Error     aux         element removed: lib/asan/libzircon-crypto.so
Error     aux         element removed: lib/sancov/libzircon-crypto.so
Warning   aux         size change for lib/libzircon-crypto.so: +1% (149.7K)
Warning   image       size change for lib/libzircon-crypto.so: +1% (149.7K)
Error     image       size change for driver/zxcrypt.so: +128% (213.9K)
Error     image       shared library removed from driver/zxcrypt.so: libssl.so
Error     image       shared library removed from driver/zxcrypt.so: libcrypto.so
Warning   tests       size change for lib/libzircon-crypto.so: +1% (149.7K)
Error: summaries do not match!

Generated with //scripts/unification/move_cpp_library.py

Bug: 36548
Change-Id: I67002d3b6adcaac2de331a73d0d5cb7c0b6f65ba
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/379196
Commit-Queue: Theodore Dubois <tbodt@google.com>
Reviewed-by: Shai Barack <shayba@google.com>
Reviewed-by: P.Y. Laligand <pylaligand@google.com>
Reviewed-by: Drew Fisher <zarvox@google.com>
Testability-Review: Shai Barack <shayba@google.com>