[wlan][lib] Remove use of private syn export
The `export` module of `syn` was not intended for public use. In the
latest version of `syn`, that module is entirely removed:
https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7

Various other projects encountered breakages due to usage of (now-
removed) `syn::export` module:
- https://github.com/nushell/nushell/issues/2867
- https://github.com/frondeus/test-case/issues/60

The current code (before this CL) will break on the next roll of
our Rust dependencies.

I noticed the compilation issue when attempting to compile with the
latest version of packages:
```
error[E0432]: unresolved import `proc_macro2::ToTokens`
 --> fuchsia/src/connectivity/wlan/lib/bitfield/src/parse.rs:6:19
  |
6 |     proc_macro2::{ToTokens, TokenStream},
  |                   ^^^^^^^^ no `ToTokens` in the root
```

Test: fx test wlan-bitfield-tests
Change-Id: I63798d3547808b7c66a3e74d02226966f3a5818c
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/469957
Fuchsia-Auto-Submit: Marc Khouri <mnck@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Reviewed-by: Kiet Tran <kiettran@google.com>