[build] Suppress -Wunused-but-set-var in simple-pt
This patch suppresses -Wunused-but-set-variable warning in
simple-pt third-party code that does not comply with.

The code that causes the issues is as the following:
garnet/bin/insntrace/print/third_party/simple-pt/call-printer.cc:215:7:
error: variable 'n' set but not used

Bug: 77973
Change-Id: Ie264c7f5604ebae5b9bc330dcd7c156c34b3f9df
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/551892
Commit-Queue: Gulfem Savrun Yeniceri <gulfem@google.com>
Reviewed-by: Shai Barack <shayba@google.com>