Revert "[usb-request] Add C++ wrapper for usb-request."
This reverts commit fe261089afc06c634a87ea230fb854a69bd49a97.

Reason for revert: This is breaking GI, as Garnet won't build due to a missing zircon/thread_annotations.h.

[9284/24541] CXX obj/zircon/system/dev/lib/usb/test/usb.usb-request-pool-test.o
FAILED: obj/zircon/system/dev/lib/usb/test/usb.usb-request-pool-test.o 
/b/s/w/ir/cache/goma/client/gomacc ../../buildtools/linux-x64/clang/bin/clang++ -MD -MF obj/zircon/system/dev/lib/usb/test/usb.usb-request-pool-test.o.d -DTOOLCHAIN_VERSION=gxqulZU837Lj_Zc8tC9te-IWOCqAYYzQSVzHLxDfl6oC -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DZX_DEBUGLEVEL=2 -I../.. -Igen -I../../zircon/system/dev/lib/usb/include -I../../zircon/system/ulib/ddk/include -I../../zircon/system/ulib/pretty/include -I../../zircon/system/ulib/fdio/include -I../../zircon/system/ulib/fdio/include -I../../zircon/system/ulib/sync/include -I../../zircon/system/ulib/zircon-internal/include -Ifidling/gen -I../../zircon/system/ulib/fidl/include -I../../zircon/system/ulib/ddktl/include -I../../zircon/system/ulib/fbl/include -I../../zircon/system/ulib/zx/include -I../../zircon/system/ulib/zx/include/lib -Ibanjoing/gen -I../../zircon/system/ulib/unittest/include -fcolor-diagnostics --sysroot=/b/s/w/ir/kitchen-workdir/out/debug-arm64/zircon_toolchain/obj/zircon/public/sysroot/sysroot --target=aarch64-fuchsia -fdebug-prefix-map=/b/s/w/ir/kitchen-workdir=../.. -no-canonical-prefixes -fno-omit-frame-pointer -g3 -Wall -Wextra -Wno-unused-parameter -Wno-unused-lambda-capture -Wno-user-defined-warnings -fvisibility=hidden -O0 -Werror -Wno-error=deprecated-declarations -fvisibility-inlines-hidden -std=c++17 -fno-exceptions -fno-rtti -Wthread-safety -c ../../zircon/system/dev/lib/usb/test/usb-request-pool-test.cpp -o obj/zircon/system/dev/lib/usb/test/usb.usb-request-pool-test.o
In file included from ../../zircon/system/dev/lib/usb/test/usb-request-pool-test.cpp:5:
../../zircon/system/dev/lib/usb/include/usb/request-cpp.h:20:10: fatal error: 'zircon/thread_annotations.h' file not found
#include <zircon/thread_annotations.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> [usb-request] Add C++ wrapper for usb-request.
> 
> The wrapper include following classes:
> * usb::Request - main wrapper around usb-request. A move only type which
> provides some additional conveniance functions.
> * usb::UnownedRequest - similar to usb::Request, but does not call
> release on delete.
> * usb::RequestPool - a pool to make reusing usb::Request objects easier.
> * usb::RequestQueue - a queue to make it easier to to store request
> while they are waiting to be processed.
> * usb::UnownedRequestQueue - Unowned variant of usb::RequestQueue.
> 
> Tested: runtests -t usb-unittest
> Change-Id: If2abcf88b41af3b6819727bd1b671b0f5565b7b2

TBR=voydanoff@google.com,teisenbe@google.com,jocelyndang@google.com,ravoorir@google.com,surajmalhotra@google.com

Change-Id: I33843886bdf5baed3b676010b12dfb1a2b2df8b2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true