[kernel] Use PinnedVmObject::reset instead of ktl::move
We're relying on ktl::move to run the destructor of PinnedVmObject
ignoring the result value, but this is triggering an error in the
tip-of-tree Clang:

    ../../zircon/kernel/arch/arm64/perf_mon.cc:515:5: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
        ktl::move(data->pinned_buffer);
        ^~~~~~~~~ ~~~~~~~~~~~~~~~~~~~
    1 error generated.

Use PinnedVmObject::reset instead which has the same effect.

Fixed: 108702
Change-Id: Id14a35a996804a9398b50032e1a4421e50591149
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/720210
Reviewed-by: Roland McGrath <mcgrathr@google.com>
Fuchsia-Auto-Submit: Petr Hosek <phosek@google.com>
Commit-Queue: Petr Hosek <phosek@google.com>