[http-client] Assert error is None
Currently we are seeing a very anemic test failure:
```
[stdout - test_fetch_http_big_stream]:
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some(200)`',
../../src/connectivity/network/http-client/integration/src/lib.rs:90:5
```

This change should provide more information when such failures occur.

Replace point accesses with destructuring while I'm here.

Multiply: http-client-integration-test
Bug: 82499
Change-Id: I1029009381f73e800deb1754833593cb702e31c9
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/571081
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Fuchsia-Auto-Submit: Tamir Duberstein <tamird@google.com>
Reviewed-by: Bruno Dal Bo <brunodalbo@google.com>