[unification] Move //zircon/system/dev/thermal to the GN build
Generated with: //scripts/unification/move_zn_element.py

scripts/unification/verify_element_move.py --reference local/initial.json:

Warning   aux         size change for test/sys/aml-thermal-s912-test: -2% (200.1K)
Warning   aux         size change for test/sys/mtk-thermal-test: -3% (160.0K)
Warning   aux         size change for test/sys/aml-thermal-s905d2g-test: -2% (217.2K)
Warning   aux         size change for test/sys/as370-thermal-test: -5% (188.0K)
Error     aux         shared library removed from test/sys/aml-thermal-s912-test: libdriver.so
Error     aux         shared library removed from test/sys/mtk-thermal-test: libdriver.so
Warning   aux         shared library added to test/sys/mtk-thermal-test: libc++abi.so.1
Warning   image       size change for driver/aml-thermal-s912.so: -4% (61.5K)
Warning   image       size change for driver/mtk-thermal.so: -4% (69.5K)
Warning   image       size change for driver/as370-thermal.so: -3% (97.5K)
Warning   image       size change for driver/aml-thermal-s905d2g.so: -3% (89.5K)
Warning   tests       size change for test/sys/aml-thermal-s912-test: -2% (200.1K)
Warning   tests       size change for test/sys/mtk-thermal-test: -3% (160.0K)
Warning   tests       size change for test/sys/as370-thermal-test: -5% (188.0K)
Warning   tests       size change for test/sys/aml-thermal-s905d2g-test: -2% (217.2K)
Error     tests       shared library removed from test/sys/aml-thermal-s912-test: libdriver.so
Error     tests       shared library removed from test/sys/mtk-thermal-test: libdriver.so
Warning   tests       shared library added to test/sys/mtk-thermal-test: libc++abi.so.1
Error: summaries do not match!

Bug: 36139
Change-Id: I3500fdd66d73808c1ec34f1a79e62ded77988482