Revert "[test spec] Introduce test resources"
This reverts commit 652256cb520a279ae4160003876372c824a3aa69.

Reason for revert: Might have broken Topaz build.

FAILED: host_x64/gen/topaz/public/dart/composition_delegate/composition_delegate_tests 
/usr/bin/env ../../build/dart/gen_dart_test_invocation.py --wd ../../../../../.. --out /b/s/w/ir/k/out/x64/host_x64/gen/topaz/public/dart/composition_delegate/composition_delegate_tests --dart host_x64/gen/topaz/public/dart/composition_delegate/composition_delegate_tests/dart --snapshot host_x64/gen/topaz/public/dart/composition_delegate/composition_delegate_tests.snapshot
Traceback (most recent call last):
  File "../../build/dart/gen_dart_test_invocation.py", line 59, in <module>
    sys.exit(main())
  File "../../build/dart/gen_dart_test_invocation.py", line 50, in main
    with open(app_file, 'w') as file:
IOError: [Errno 21] Is a directory: '/b/s/w/ir/k/out/x64/host_x64/gen/topaz/public/dart/composition_delegate/composition_delegate_tests'

Original change's description:
> [test spec] Introduce test resources
> 
> Valid only for linux/mac tests, this abstracts the metadata dance that
> needs to take place in order for the infrastructure to respect the
> runtime dependencies that test take (i.e., so the former will be
> available on the bots when the test is executed).
> 
> Resources dictate where in source or the build directory files may be
> placed, relative to the test executable.
> 
> Note: this change moves the test director of dart_test from
> $root_out_dir to $target_gen_dir, as relative paths in the test are
> treated as relative to the latter.
> 
> Change-Id: I8be94f859c400875801ebadbdd83c9fc9122c1f1

TBR=phosek@google.com,juliehockett@google.com,joshuaseaton@google.com

Change-Id: Ic3396cd8bc3bd25254af63545b4b426199a30a97
No-Presubmit: true
No-Tree-Checks: true
No-Try: true