Revert "[fit] Add fit::sequencer for ensuring sequential execution order."
This reverts commit 7baf23bcf61351ddc9965a0fdc656a9298b5a221.

Reason for revert: blocking Zircon roll
...
sequencer.h:47:14: error: use of class template 'fit::bridge' requires template arguments
...

Original change's description:
> [fit] Add fit::sequencer for ensuring sequential execution order.
> 
> Test: fit-test
> Change-Id: I2f44bdba931f8a7bb9a0917549c1eb7c43858b70

TBR=jeffbrown@google.com,thatguy@google.com

Change-Id: I30bc48691e32dca236a0164f002135d46f8d4690
No-Presubmit: true
No-Tree-Checks: true
No-Try: true