[fx] Begins transition to device-finder for discovery.
This also sets up a soft transition to rename dev_finder to
device-finder for more correct naming. This is not intended to be
an exhaustive replacement of netaddr w/ device-finder, but to implement
the minimum before changing existing invocations of `fx netaddr` to `fx
device-finder` or the more portable `fx get-device-addr`.

Test: See below

On Linux desktop w/ one device on local subnet:
---------------------------------------------------------------

$ fx clean && fx get-device-addr
`` Leads to error

$ fx set core.x64 && fx build && fx get-device-addr
`` Leads to device discovery on local network.

$ fx -d device shell
`` Times out, but attempts to connect to device on network.

$ fx shell
`` Times out, but attempts to connect to the only device on network.

$ fx shell # Device unplugged
2019/12/17 12:30:38 no devices found
ERROR: Multiple devices or no device found.  Try "fx -d=DEVICE_NAME shell" or "fx set-device DEVICE_NAME"

$ fx serve
2019-12-17 15:11:45 [serve-updates] Device up
2019-12-17 15:11:45 [serve-updates] Registering devhost as update source
2019-12-17 15:11:46 [serve-updates] Ready to push packages!
2019-12-17 15:11:46 [serve-updates] Target uptime: 15

On Mac:
---------------------------------------------------------------

$ fx clean && fx get-device-addr
`` Leads to error

$ fx set core.x64 && fx build && fx get-device-addr
`` Leads to device discovery over wifi

$ fx -d device shell
`` Attempts to shell into device (fails due to bad credentials).

$ fx shell
ERROR: Multiple devices found.
ERROR: Please specify one of the following (check network if this fails):
ERROR:  fe80::2e0:4cff:fe00:2140%en0 crush-comma-jog-snap
ERROR:  fe80::2e0:4cff:fe05:4f5e%en0 widen-veto-sugar-yo-yo
ERROR:  fe80::2e0:4cff:fe03:59c%en0 yard-nacho-baton-slob
ERROR: Multiple devices or no device found.  Try "fx -d=DEVICE_NAME shell" or "fx set-device DEVICE_NAME"

$ fx shell # Networking disabled.
2019/12/17 12:19:59 no devices found
ERROR: Multiple devices or no device found.  Try "fx -d=DEVICE_NAME shell" or "fx set-device DEVICE_NAME"

Change-Id: Iacfa6a5c40925483a342b7d69f9a807e3914f8f9